### ISSUE TITLE
Make the data into the format required by the data team

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#112]
See the requirements here. https://github.com/ONSdigital/SDG_11.2.1/issues/55

This should be done before the proportion of people with disabilities is calculated. 

Additional requirement:
- output data with the calculation year in the file name, e.g. "public_transport_accessibility_2019.csv"

**Comment by james-westwood** [comment]
Aiming for this table shape

![image](https://user-images.githubusercontent.com/49570694/150132655-3ca238de-8d06-4239-a100-c2bce45f835a.png)

**Comment by james-westwood** [comment]
Update: I have created a more comprehensive data example layout in an open document spreadsheet 


[JW_Example_output_data.11.2.1.ods](https://github.com/ONSdigital/SDG_11.2.1/files/7912504/JW_Example_output_data.11.2.1.ods)

**Comment by jwestw** [comment]
Thanks Tom for the ideas here: 

`age_served_df` 
id_vars: age
value_vars: Total, Served, Unserved. Served%, Unserved%


AGE, VARIABLE, VALUE
0-4, Total, 154
0-4, Served, 323
0-4, Unserved, 865
etc.

**Comment by james-westwood** [comment]
Making good progress. See the commits in draft PR : https://github.com/ONSdigital/SDG_11.2.1/pull/151

So far I have reshaped:
- age df
- sex df
- disab df

Now working on the totals for the LA with `la_results_df` and `do.reshape_for_output()`

**Comment by james-westwood** [comment]
Note to self: just noticed that the percent "Total" row is missing. For example, all records for the age group 55-59 are:

![image](https://user-images.githubusercontent.com/49570694/151575738-48e0bc57-36c3-4a05-ad69-b43f4714c72d.png)

This needs to be fixed.

**Comment by james-westwood** [comment]
Note: `sex_all_la` is currently still not processed into the format required by the data team. 

All other dfs look like they could be vertically stacked.

**Comment by james-westwood** [comment]
@Frensisbras This ticket is nearing completion and therefore we are starting to output data from this project in the format that the data team needs for the SDG Platform. 

The attached csv is our first proper output in this form. I have just run the calculation for some randomly selected local authorities. Please can you see if:

- the shape/format of the data is what you expect? 
- all the dimensions that you are expecting are covered
- the values you are expecting is in the right columns (especially have I got Unit Measure and Unit Multiplier the right way round?)

Also there might be an issue around "Non-disabled" data. I was not sure if we needed to list that, or whether that's just covered in the other data. A point that probably needs discussion.

It's been a long road to get here, so I hope the data is what you're expecting at this stage! I would welcome feedback from others in the data team too. 

[All_results.csv](https://github.com/ONSdigital/SDG_11.2.1/files/8005055/All_results.csv)

**Comment by james-westwood** [comment]
Since there are individual tickets to handle the feedback (and one has already been dealt with, via #179 ) I am going to merge #151 to close this issue.
