### ISSUE TITLE
Make Sphinx Documentation for version 1.0

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#118]
[Sphinx ](https://www.sphinx-doc.org/en/master/)is a documentation generator tool that can help us make neatly presented documentation for the 11.2.1 Public Transport project. 

Pages we might want to create in the documentation include:
- Introduction to the project, including background, aims etc (like the current README)
- Developer documentation, including:
    -  how to set up an environment and run the code (part of the current README)
    - what each function does
- Method/Calculation write up

**Requirements for this ticket:**

- [x] Using output of #158 use Sphinx to create technical documentation
- [x] Split up the existing README to make the intro page of the user documentation and technical documentation
- [x] Create holding (lorem ipsum type) pages for anything we don't have content for right now
- [x] Work out a way to display these pages like our readme is currently.

**Comment by jwestw** [comment]
There is a branch for this already: https://github.com/ONSdigital/SDG_11.2.1/tree/sphinx_docs_%23118

**Comment by paigeh1** [comment]
Currently waiting for docstrings to be updated. A holding page for methodology write up has also been created. Focusing on #194 to get the page hosted on github.

**Comment by james-westwood** [comment]
I think this is done. @nkshaw23 would you agree? If so, please close the issue.

**Comment by nkshaw23** [comment]
Agree - closing.
