### ISSUE TITLE
Calculate the 2019 population estimates by age

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#120]
@musachirikeni

Now we have calculated the population estimates for people with disabilities I think I can apply the same method to estimates of the population by sex. However it seems to me that due to the ever changing nature of age demographics, the same method will not work with the age disaggregation. Do you know if there is either:
- an established method for estimating how each of the age groups will grow in a growing population? (preferred option)
- datasets that already offer these estimates (I fell sure they must exist)  

Thanks for your help

**Comment by MusaChirikeni** [comment]
Hi James. The mid year population estimates already have this breakdown of population by age and sex. So this is naturally factored in when they release a revised version or next iteration of this data set.

**Comment by james-westwood** [comment]
Thanks @MusaChirikeni That's really helpful.

**Comment by james-westwood** [comment]
I am planning to:
- get all the links for the 2019 population estimates
- import all the csvs
- get them into either a dataframe, or (more preferably but probably more long-winded) an SQL database
- make the disaggregation calculations for 2019 for age and sex

**Comment by james-westwood** [comment]
A bodge workaround: manually extract all the data via excel to csv. This would work for one year, but would be error prone and fiddly for multiple years. Not what we want for an integrated pipeline. 

To automate this, it is probably going to be best done via the `any_to_pd` function

This would probably mean doing the following:
- simplifying the internal `_import_extract_delete_zip` function so it only extracts and writes the needed file(s) locally then cleans up. i.e. not returning a pd_df at the moment it is doing returning the df via `_csv_to_df` but obviously this wouldn't work for and xlsx file
- create a `_xls_to_df` function that can be called similarly
- build some logic somewhere (probably in the main `any_to_pd`  function) to recognise which function to apply on which file times according to the file extension.

**Comment by jwestw** [comment]
Coming back to this after quite a long time off of working on it. 

Looking at what was done previously on this branch: https://github.com/ONSdigital/SDG_11.2.1/tree/import_2019_estimates_%23120

I this commit - https://github.com/ONSdigital/SDG_11.2.1/commit/e793d66c553acee0db2cc881bed00a2ce68a4e43 - 
in SDG_11.2.1_main.py lines 73-84, I am running a for loop to attempt to download and extract all the zip files which contain the data files and extract them. However, the method I am using there is `_grab_zip` which was meant to only be an internal function used by the `any_to_df` function. For some reason, the zip files that are being grabbed and saved locally are not valid - neither Python nor Windows own zip file utility can open them. That problem needs to be looked into. 

Really, the whole download --> save --> extract -- return dataframe process should be handled by the `any_to_df`function. I think the reason that I didn't do this, is unlike the other zip files I am downloaded (for the stops data for example) these zips contain csv files. 

As I mention in an earlier comment, I know that I could just download these and turn them into a csv with Excel, but I want this to work with population estimates from other years. And the aim of the project is to have an integrated data pipeline anyway, rather than just an MVP with manual work arounds. 

The zip files I am downloading here contain Excel files with multiple tabs. This could be handled by Pandas natively, or might be better handled by [Databaker](https://databaker.sensiblecode.io/). I am not sure if that's overkill though.

**Comment by james-westwood** [comment]
This is a stale and obsolete issue. Closing.
