### ISSUE TITLE
Filter out stops with irregular service using timetable data

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#123]
This issue is dependent on https://github.com/ONSdigital/SDG_11.2.1/issues/60 and https://github.com/ONSdigital/SDG_11.2.1/issues/212

According to the official methodology, a consideration of the frequency of service needs to be taken into consideration. I believe this will be possible if we import transport timetable data, and filter out stops that do not reach a certain frequency criteria. 

The requirement as stated is that there should be:

_"Public transport with frequent service during peak travel times"_

The way other countries have handled this, e.g. [Estonia](https://www.efgs.info/11-2-1-estonia/), is to filter for stops that reach the requiment as follows:

_"the frequency of public transport is at least 1 departure per hour between 6:00 am – 8:00 pm"_

and 

_"For analysis, we chose Wednesday and included all the trips operating on Wednesdays.

The next step was to create a crosstable, where each row showed the STOP ID and columns showed the operating hours. Next, we selected only hours 6:00 am – 8:00 pm and hours with at least one trip. 2,192 stops out of 16,394 stops remained"_

Similarly [Norway](https://www.efgs.info/11-2-1-norway-test-page/) stated that convenient access was consider if the stop was _"within 500 m straight line to stops with at least 1 hour frequency"_

**Requirements for the developer:**
- Bring in timetable data to filter out stops that are not regularly serviced. This may require:
    -  Find out where timetable data is available. There may be other sources, but one is [Traveline data (TNDS)](ftp://ftp.tnds.basemap.co.uk/)
    - This should be covered by https://github.com/ONSdigital/SDG_11.2.1/issues/60
    - If using TNDS, make an [FTP](ftp://ftp.tnds.basemap.co.uk/) request to get the timetable data for all stops on the naptan data (James has access keys)
- Parse xml data into dataframes. This should be covered by https://github.com/ONSdigital/SDG_11.2.1/issues/212
- **(This ticket)** Filter the stops out that do not meet the condition. 
    - The condition is "1 departure per hour on a Wednesday, between 6am and 8pm".

**Comment by james-westwood** [comment]
@ivyONS @MartinWoodONS We were wondering if you had any thoughts on methods for filtering the stops/stations according to the transport service frequency. 

As you can see, I have outlined a method in the comment above under **"Requirements for the developer"**, but I feel that making an FTP request for data might not be the best method. We actually make use of FTP already in our project but we would prefer to use an API I think. 

If you do have any suggestions we are looking for:
- alternative data sources (or a validation of the one we are considering)
- any suggestions for a method or approach that you might have that differ from the above outline
- any methods/code that you already have for filtering stops

**Comment by james-westwood** [comment]
@MartinWoodONS Thanks so much for your input. 

I have had a look on the FTP server and linked a couple of related tickets which would be dependencies of this. 

The data is made up of zip files (I think one for each region of the England and Wales, like SW, SE, WM...) containing xml files. 

At the moment I am thinking of just manually downloading those and parsing the XML into a big dataframe, then applying the filter (this ticket).

**Comment by nkshaw23** [comment]
Duplicated by #257
