### ISSUE TITLE
Make sure the entire population data for the entire UK is being used for the calculation

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#129]
Currently the population data that is being used for the calculation is limited to just West midlands or possibly Birmingham. This needs to be expanded to include all regions of the UK to calculate the numbers for version 1.0.

**Comment by Antonio-John** [comment]
[Census 2019 population estimates data links URLs:
South West, England. : Source Page
Yorkshire and humber. : Source Page
East, England. Source Page.
South East, England. Source Page.
East Midlands. : Source Page
North West, England. Source Page
West Midlands, England . Source Page
Wales. Source Page
North East, England. Source Page
London, England. Source page](https://github.com/ONSdigital/SDG_11.2.1/issues/128#:~:text=Census%202019%20population%20estimates,London%2C%20England.%20Source%20page)

**Comment by Antonio-John** [comment]
Full pipeline run successful on my machine. Had to download data from above and create a 2011 folder to put the centroids data in.

**Comment by Antonio-John** [comment]
Have tried to put UK wide data/cals first. Then there is a list of LA's which can iterate through all the LA's and then put results into a dataframe and export.

**Comment by james-westwood** [comment]
This was completed with PR https://github.com/ONSdigital/SDG_11.2.1/pull/146
