### ISSUE TITLE
Document virtual env creation process. Add to the readme

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#134]
It is important to have good documentation for both users of the data and users of the data processing pipeline. Currently the instructions for setting up a virtual environment are out of date and do not include things like the use of requirements.txt to install the dependencies. 

Since the virtual environments we create and develop in are conda environments, we use `conda install...` to install the dependencies, but a few are not available in conda channels it seems, so we use `pip install...` for those. These particularities need to be documented. 
 
It would be great to renew/update this section of the documentation. 

To be included in this readme:
- cloning repo (for things like ssh key creation, just link to resources)
- virtual env creation (might want to include a little section on why we use virtual envs)
- installing dependencies 

### Steps in this task:
- create yourself a branch on github 
    - (go [here ](https://www.wikihow.com/Create-a-Branch-on-GitHub#:~:text=How%20to%20Create%20a%20Branch%20on%20GitHub%201,Press%20%E2%86%B5%20Enter%20or%20%E2%8F%8E%20Return.%20See%20More.) for a reminder) 
    - use a descriptive name that represents what you are doing in this ticket
    - include the issue number (134) somewhere in the name
- Use `git fetch` on your local machine to get the branch that you have created (and all other remote updates)
- Use VS Code to update your readme.
    - Tip: use a [markdown previewer extension](https://code.visualstudio.com/Docs/languages/markdown#:~:text=VS%20Code%20supports%20Markdown%20files%20out%20of%20the,existing%20Markdown%20file%20and%20start%20working%20with%20it.) if you want to see how your markdown file will look
- Save your .md file and stage/commit/push the changes. 
    - Check [here ](https://learn.sourcegraph.com/how-to-commit-code-to-a-git-repository-with-visual-studio-code) for a reminder of how to do this in VS Code
    - Also, remember it's worth knowing and understanding how to do this on the command line

You can keep notes in the comments of this ticket and you can tag me or ping me on Teams if you need help. 

Note: 
- It seems feather-format might be installable via conda https://anaconda.org/conda-forge/feather-format
- Since outputting as Excel is not a requirement, we might be dropping gptables from the requirements.

**Comment by paigeh1** [comment]
Note to self to remember to mention that anaconda will need to be installed for this process.

**Comment by paigeh1** [comment]
Closing this issue due to merging the pull request earlier.
