### ISSUE TITLE
Check pop weighted centroid data

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#139]
Check whether population weighted centroids get updated with the population estimates or whether we use the same ones as the census year for year by year calculations

- Do this in the same way that I have with the population, i.e. use `pop_year` as a variable to get into the correct data dir
   - data/pop_centroids/{year}
- data is from here: https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(CTD_OA)

**Comment by james-westwood** [comment]
@musa-chirikeni 

I think this is a question for you again - somewhat similar to what Antonio was asking here: https://github.com/ONSdigital/SDG_11.2.1/issues/152#issue-1119122299

We are now starting to make calculations for each year. Mainly we have been calculating 2011 (cencus year) and 2019 (a year which we have used population estimates to calculate). 

Question: As we make calculations for non-census years using the population estimate data, will the population-weighted centroids also change? I imagine they will not only change in number (which will be accounted for by the population estimate data) but also in location. Are year-by-year population weighted centroid data available? If so where from? If not, how important is this? 

Thanks for your help.

**Comment by james-westwood** [comment]
I have looked into this and can't find year-by-year population weighted centroid data for output areas. I only found 2001 and 2011 suggesting that there isn't any in non-census years. 

Created a branch for this: https://github.com/ONSdigital/SDG_11.2.1/tree/check_pop_centr_data_%23139

**Comment by MusaChirikeni** [comment]
That is correct, population weighted centroids are only available for the census years 
2001 and 2011. 

The centroids will only change on a new iteration of census geographies created based on the 2021 census where certain population thresholds might be adjusted slightly. 
Until then, any population based analysis would be calculated by taking the OA pop estimates from your chosen year and merging them with the 2011 OA pop-weighted centroids. 

As you know, OAs reflect the residential population and we use the pop-weighted centroids to identify locations
which best represent where residents live within OAs.
Our assumption with this method is that if an OA is well served for transport then the OA pop-weighted centroid should be captured within the 500m buffer for all stops. If not captured by the buffer, the implication is that the OA's population will not be included for the overall LADs summary stats.

In a way, the limitation is that some OA pop-weighted centroids will shift once in every ten years when the new version of OAs are created after each census.
However, this is not likely to have any severe impacts on the overall results as the adjustments should be minimum with the OAs and OA pop-weighted centroids for 2021 census.

**Comment by jwestw** [comment]
@MusaChirikeni That's amazing. Thank you for your input. 

Before closing this ticket I will just make one development requirement:
- Develop config setting to choose OA pop-weighted centroids year (2001, 2011, 2021)

**Comment by jwestw** [comment]
Pipeline will not run since branching off-of master, and data is missing. Apparently this is what's needed: 
https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2021-uk-bfc/explore
Local Authority Districts (December 2021) UK BFC Boundaries
