### ISSUE TITLE
QA: Check disabled data

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#140]
QA: 
- Check that disabled a lot and disabled a little don't intersect. Data source is "nomis_QS303.csv"
- Also check that the numbers output by the analysis done by `served_proportions_disagg` and the results of `reshape_for_output` are correct
    - do they contain the right number of observations?
    -  are they indeed just observations for disabled people (i.e. not "non-disabled" status people)?

**Comment by Antonio-John** [comment]
Original columns in disabled_prop_df which come from the nomis_QS303 file are:
-All categories: Long-term health problem or disability
-Day-to-day activities limited a lot
-Day-to-day activities limited a little
-Day-to-day activities not limited

**Comment by Antonio-John** [comment]
The disabled population total comes from adding up "Day-to-day activities limited a lot" and "Day-to-day activities limited a little". These are then merged onto the usual residents population. Confusingly it seems that the columns of the usual residents pop (by OA) is the same as All categories: Long-term health problem or disability which I don't really understand how that can be possible.

**Comment by james-westwood** [comment]
@Antonio-John Hmm it sounds like we need to speak to somebody who understands the Nomis data. Previously Musa contacted someone who knew the data really well, but I can't remember who that person was now. Perhaps reach out to him again and ask him if either he, or the person he contacted would be able to help on this issue.

**Comment by jwestw** [comment]
@Antonio-John I remember there was a conversation which may be relevant to this ticket: https://github.com/ONSdigital/SDG_11.2.1/issues/44

**Comment by jwestw** [comment]
This has been covered in #173
