### ISSUE TITLE
Limit population dataframe to local authority

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#144]
Currently the population dataframe that is being imported (`Wmids_pop_df`) is being 'limited' or filtered on by merging with the `bham_LSOA_df` to create a `bham_pop_df`.

As we are moving away from Bham-only calculations in ticket #129 we should not be using this method. 
Due to the work in ticket #138 we will probably no longer have a LSOA df, but have LA data column in the dataframe. 

The work for the ticket is to:
- stop using `Wmids_pop_df` at all, and instead only using the `whole_nation_pop_df` instead
- do not filter the population dataframe using the LSOA, but filter on the LA column by local authority name instead

**Comment by jwestw** [comment]
This work was covered in other tickets. 

- Issue https://github.com/ONSdigital/SDG_11.2.1/issues/129 and PR https://github.com/ONSdigital/SDG_11.2.1/pull/146 covered the use of an LA df and filters the whole nation df instead using the values in the LA column.
- Work in issue https://github.com/ONSdigital/SDG_11.2.1/issues/130 created the needed LA df
- And work in #112 covered the mapping of OA's to LA's, meaning that LSOA's were not needed
