### ISSUE TITLE
Make a decision on how to process the data

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#145]
@Antonio-John @Mark-Simons-ONS 
This is a discussion to be had between us. 

My guess is that processing the result for the whole nation at once will take a long time. I have never done it so I do not know. So should we be able to specify any one local authority to process at a time, e.g. "Swansea" or limit to a list, e.g. ["Kingston upon Thames", "Lambeth", "Lewisham"] so we can check different areas are calculating okay, and also run the pipeline a bit quicker when we are developing.

The question is should we:
- Calculate each of 379 local authorities one by one and concatenate the results afterwards
- Calculate the whole nation at once in one big computation and then aggregate the results by local authority for reporting

You can add your thoughts on this issue in the comments and/or we can chat on a Teams call about it. Either way we should write what we decide in the comments.

**Comment by Antonio-John** [comment]
From a development point of view I think it's easier to calculate results 1 by 1. That way we could have a list like you have mentioned. 

Furthermore, it could give us the functionality further down the line off: If we wanted to do all LA's in Wales (or any group of LA's), we could just pass that list through.

**Comment by jwestw** [comment]
The for loop going through the local authorities is good for the time being but I think we should attempt a whole-nation-at-once calculation. I think it would be much faster. 

I have created an issue for this: https://github.com/ONSdigital/SDG_11.2.1/issues/159  

I will now close this issue.
