### ISSUE TITLE
QA: Do LA Boundaries move?

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#152]
On the SDG 11.2.1 project we are looking to measure the amount/proportion who have access to public transport on a local authority basis. We currently pull in 2011 census data to calculate population centroids on an OA11 basis. These are then merged into a dataframe with local authority. Currently, we are using LA21 boundaries/coordinates to determine whether an OA lies in an LA. 

Our questions are: 
-Is it appropriate to be doing this given the time difference from the census 2011 and the current LA21 boundaries?
-Do these local authorities change boundaries often? and if they do how do we know if they have changed?

Any advice would be appreciated please @MusaChirikeni

**Comment by Antonio-John** [comment]
Have spoken with Musa through teams (03/02/22) Hadn't got the github notification but will have a look at the question and get back to me.

**Comment by MusaChirikeni** [comment]
If you're using 2011 census data then you're better off using the 2011 Local Authority Districts to report for the year 2011. 

The use of 2011 Nomis data was strictly for extracting data only collected in the census such as disability and rural which could then be turned into proportions and applied across the years until the next available census data on those variables. 
For example, using the 2011 census data to find the 2011 proportion of people living with disabilities then applying that proportion onto the 2015 population OA estimates to summarise by the 2015 LAD boundaries for the 2015 figures.

The local authorities do change boundaries quite often which can make it a bit difficult to do direct comparisons across the years for areas subject to change.
It is therefore advised that you always summarise the OA population estimates using the LAD boundaries from corresponding years.

Seeing as you're looking for a more recent calculation I would suggest using the latest available population estimates 
which is currently the mid-2020 for the 2011 Output Areas and can be found here:
https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/bulletins/annualsmallareapopulationestimates/mid2020/relateddata

The version of the LAD boundaries you're looking for is found here:
https://geoportal.statistics.gov.uk/datasets/local-authority-districts-december-2020-uk-bfe/explore?location=55.339986%2C-3.313872%2C6.43

Happy to talk through this if needed.

**Comment by james-westwood** [comment]
Thank you @MusaChirikeni . I will let Antonio continue to work on resolving this issue.

**Comment by Antonio-John** [comment]
Thanks as well for your response @MusaChirikeni. I can create a new ticket on the board which incorporates the data suggested above @james-westwood ?

**Comment by jwestw** [comment]
I think with the creation of #154 this ticket can be closed.
