### ISSUE TITLE
Handle zeros in `served_proportions_disagg`

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#153]
When the population is zero (for example in the city of London there are zero rural population), the `served_proportions_disagg` function will error. 

This is probably also the case in SDG_11.2.1_main.py where `la_results_df` is being calculated.

**Comment by jwestw** [comment]
- Zeros could occur in total_pop especially when dealing with 100% rural or 100% urban populations. 
- Wanted behaviour: to output the following:
(if total_pop ==0) 

Total: 0,
Served: 0,
Unserved: 0,
Percentage served: NaN
Percentage unserved: NaN


- Ask the SDG data team if Nan, Null, 0 or other is appropriate

**Comment by james-westwood** [comment]
Created a branch for this: https://github.com/ONSdigital/SDG_11.2.1/tree/handle_zeros_%23153

Branched from 112 to capture some of the most important recent changes that I have been working on.

**Comment by james-westwood** [comment]
Looks like the new code is working. In the case of the LA "City of London" there are no inhabitants in "Rural" designations, so the total population (rural) is 0. The `served_proportions_disagg` function. Likewise, in the same LA, the number of people who are unserved by public transport is 0 too, and the calculations don't fail here either.    

![image](https://user-images.githubusercontent.com/49570694/153639128-2e6e66a9-292c-4ad1-b607-71657dce85f6.png)

**Comment by james-westwood** [comment]
@[quartm](https://github.com/quartm) 

The problem tackled by this ticket was that it was running into [ZeroDivisionError](https://docs.python.org/3/library/exceptions.html#ZeroDivisionError) due to the denominator `total_pop` occasionally being zero. For example, the population of individuals categorized as "rural" in the City of London, was 0. 

[The above comment ](https://github.com/ONSdigital/SDG_11.2.1/issues/153#issuecomment-1033945996) was the result of a discussion with my project team.  In the value column either 0 or `None` which turns into a blank in the csv, are being output.

I need to check with you that outputting 0 and a None (turning into a blank) is acceptable. 

For each "category" of population, e.g. age range "0-4" or having the sex "male", the total population is calculated.

```python
total_pop = int(pop_df[col].sum())
```
where `col` here is the category e.g. "0-4".

Then the numbers of people who are served and unserved by public transport are calculated too:

```python
# Served pop
servd_pop = int(pop_in_poly_df[col].sum())
# Unserved pop
unsrvd_pop = int(total_pop-servd_pop)
```

The `pop_in_poly_df` is data showing which population centres fall inside of and outside of public transport service zones. 

Then finally the percentages of each of the above are calculated. The code for this is as follows:

```python
# Get percent served
pct_servd = round((servd_pop/total_pop)*100, 2)
# Get percent unserved
pct_unserved = round(((total_pop-servd_pop)/total_pop)*100, 2)
```

So then the final output is fed into a dataframe and outputted to csv, as seen in comment  https://github.com/ONSdigital/SDG_11.2.1/issues/153#issuecomment-1036443665

Do you think the output, in terms of zeros and blanks, is acceptable?

**Comment by quartm** [comment]
Hi James, 

Thanks for flagging this issue. Yes I think that including'0's and 'none's is a sensible approach and is acceptable for our purposes. 

Thanks,
Max

**Comment by james-westwood** [comment]
Okay I have changed the behaviour to output None (for percentages when there is no result) and 0 when the number of individuals is zero. 

![image](https://user-images.githubusercontent.com/49570694/154479824-7461721e-a120-4f7f-95c9-fa1d8889e6e2.png)


Tested with City of London.

**Comment by james-westwood** [comment]
This was done ages ago
