### ISSUE TITLE
Write up method of calculation for this project

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#156]
Write up the method of calculation so an subject matter expert can understand the steps that the calculation goes through and the data sources that are used. 

Useful links, including example method write-ups:
- https://datasciencecampus.ons.gov.uk/using-satellite-imagery-to-report-changes-to-water-bodies-for-sdg-6-6-1/ 
- https://datasciencecampus.ons.gov.uk/projects/quality-and-methodology-extent-and-change-of-surface-water-statistics/
- https://www.ons.gov.uk/economy/environmentalaccounts/articles/usinginnovativemethodstoreportagainstthesustainabledevelopmentgoals/latest
- https://www.ons.gov.uk/economy/inflationandpriceindices/methodologies/identifyingfoodpriceanomaliestosupportthesustainabledevelopmentgoals
- https://github.com/ONSgeo/sdg-15-1-2
- https://www.efgs.info/11-2-1-estonia/

**Comment by jwestw** [comment]
Write up:

### Data
- [ ] Sources: Public transport stop data
- [ ] Function of data and definitions
- [ ] Data quality, limitations and assumptions

### Calculation process
- [ ]  (1) Geocoding the population data
- [ ]  (2) Delimitation of urban areas
- [ ]  (3) Computation of service areas
- [ ]  (4) Calculation of population within service areas
- [ ]  (5) Disaggregations

**Comment by jwestw** [comment]
To ask SDG Data team

- Is there a set format this needs to be in
- Is there a place it will be displayed or linked to on the SDG gov website?
- Does the above https://github.com/ONSdigital/SDG_11.2.1/issues/156#issuecomment-1033677090 cover everything?

**Comment by quartm** [comment]
@jwestw 

I think the way we publish the outputs (datasets, analysis and methods information) from this project need to be considered carefully as its the first time the data gap will be filled and will be classed as 'experimental statistics'. As such, I'll come back to you once those conversations are underway and keep you in the loop.

On the write-up structure you've proposed I think that you've covered the majority of methodological considerations that would be covered (if we were to publish the information in the form of a QMI document for instance). However I did notice a couple of things that may need to be added to fit that structure:

- A short section on "How we quality assure and validate the data", this would not need to be a lengthy text, it just needs to outline the checks that have gone into the data production process.
- A section on the strengths of the data section (as well as limitations that you already mention).
- Potentially a short section on differences with the UN data under the banner "Coherence and comparability" and any other similar data you are aware of. This also doesn't need to be lengthy, I think we just need to mention that we are aware of these other data and outline the main differences.

Let me know if anything I've mentioned doesn't make sense.

Max

**Comment by james-westwood** [comment]
Adding research resources as I find them:
- https://ec.europa.eu/regional_policy/sources/docgener/work/012020_low_carbon_urban.pdf
- https://www.thebusinessdesk.com/westmidlands/news/2061511-poor-access-to-public-transport-%E2%80%98costing%C2%A0birmingham-3.6bn-in-productivity%E2%80%99
- https://www.realjourneytime.co.uk/ (based on actual travel times, rather than timetabled journey times for Birmingham)
- https://citymonitor.ai/transport/buses

**Comment by jwestw** [comment]
### Notes on Data quality, limitations and assumptions

#### List of data to be described:

- Stops/NAPTAN data
- Population data
  - OA data from census
  - OA data from population estimates
  - Population weighted centroids
  - The file used for OA to LA mapping


- Data should be described (what columns there are, availability and summary of what it is), URL given. 
   - description can be taken from the source (e.g. NAPTAN website)
- Link to any quality and methodology resources/standards that the data adheres to, e.g. [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/)
- Possibly link to code which extracts the data, or refines it. 
    - Could link to the particular page/tab on our github hosted pages
- Any limitations that we see in the data e.g.: 
    - Pop weighted centroids not being granular enough
    - Population estimates have not figures on disability, so we calculated them ourselves
    - NAPTAN data is only updated when Local Authorities are ready to provide the data. Could be out of date?

**Comment by jwestw** [comment]
### Notes on Methodology

- How we classify disability
- How we calculate the buffer
- Network/path calculation (not done, how it would be done, potential limitations and improvements)
- Calculation process
 - Geocoding the population data
     - ONS's method for doing this - census methods can be linked to
     - How many geocodes (centroids) there are
     - Joining the OA population data with the OA population weighted centroid table (which contains location data - need to check this)
 (2) Delimitation of urban areas
 (3) Computation of service areas
 (4) Calculation of population within service areas
 (5) Disaggregations

**Comment by jwestw** [comment]
Plots we need:

- calculation of service areas - buffering. Points to polygons

**Comment by james-westwood** [comment]
The comparison of UK and EU methods could be included in the write up. 

https://github.com/ONSdigital/SDG_11.2.1/issues/175#issuecomment-1119448056

**Comment by james-westwood** [comment]
This has all been completed.
