### ISSUE TITLE
Create geographical plots for method write up

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#157]
To **illustrate** the steps and intermediate steps that calculation goes through, it would be good to have some graphical outputs. 

Plots that would be useful could include:

1. stops and their service areas
2. output areas and population weighted centroids within them
3. service areas with population weighted centroids both within and outside of them

Plots may be produced using geopandas and geoplot or, if a GUI is prefered, then [QGis](https://www.qgis.org/en/site/)

Some useful geopandas and geoplot related links:
- https://towardsdatascience.com/plotting-maps-with-geopandas-428c97295a73
- https://geopandas.org/en/stable/gallery/plotting_with_geoplot.html
- https://geopandas.org/en/stable/docs/user_guide/mapping.html

**Comment by jwestw** [comment]
Plots we need:

calculation of service areas - buffering. Points to polygons
Calculation of transport capacity - shade colour highlighting points of LAs on a map?
Future ideas:

Plotting points that have one service per hour on a weekday
Tables that could be useful:

Output an aggregated version of those with transport capacity who are disabled/not disabled, age, and sex as shown in [Estonia's write up](https://www.efgs.info/11-2-1-estonia/).

**Comment by Antonio-John** [comment]
Had a random go at plotting the service areas for Hull and comparing to images of the LA. Looks like the calculation seems to make sense!


![image](https://user-images.githubusercontent.com/74070596/166488333-c2a6686c-244e-4baf-986b-16848b33a510.png)

**Comment by nkshaw23** [comment]
Attached some plots created in QGIS - can share the geopackage that contains all the layers if people would like. 

Method plots designed to show process. Done for York as could get a good mix of city / rural output areas. Should be viewed in the following order:

![LA](https://user-images.githubusercontent.com/20166290/174642857-7f793ed7-d4c1-4bd2-98e3-fa8820d4d83c.png)
![output_areas](https://user-images.githubusercontent.com/20166290/174642877-403dc9ff-f862-419f-b3aa-71ccde0a6727.png)
![stops](https://user-images.githubusercontent.com/20166290/174642892-0640e442-8c6b-4eb2-9ff8-5ca3f0be4c5f.png)
![stops_buffer](https://user-images.githubusercontent.com/20166290/174642906-f264821f-544c-4be4-9c6d-ffccb66a2876.png)
![pop_centroids](https://user-images.githubusercontent.com/20166290/174642922-a5aab101-807f-495e-8468-e68bdddb4417.png)
![output_areas_counted](https://user-images.githubusercontent.com/20166290/174642935-029cbd18-b1b0-4277-bb32-1a966f18cc42.png)
![output_areas_not_counted](https://user-images.githubusercontent.com/20166290/174642950-040987c7-58e0-4864-8eee-b8c7dac3a282.png)

**Comment by jwestw** [comment]
@nkshaw23 These look excellent. Really informative at a glance and will also really help explain the methodology write up. I would love to know how you have done them and whether the other needed-plots that I have listed above can be done by the same method(s).

**Comment by nkshaw23** [comment]
I can show you tomorrow on the call - but done in QGIS.

Happy to discuss other plots, but the nationwide ones would be difficult to present well due to data sizes..

**Comment by nkshaw23** [comment]
Making note to add this diagram into the docs before closing the ticket.

**Comment by nkshaw23** [comment]
Adding extra  images (with legend) and additional rural / urban image before closing.

![creating_transport_areas](https://user-images.githubusercontent.com/20166290/180426794-fcffc845-af3d-4e39-971a-5441e823715c.png)
![geolocating_transport_stops](https://user-images.githubusercontent.com/20166290/180426768-fd6dbfab-183f-4fec-9cc0-4ecb1116e28d.png)
![serviced_population](https://user-images.githubusercontent.com/20166290/180426780-b706eaf9-0148-4a93-934c-7b3538e82538.png)
![serviced_population_full](https://user-images.githubusercontent.com/20166290/180426783-65db382f-c25e-40ef-9142-81ca782428fc.png)
![ruc](https://user-images.githubusercontent.com/20166290/180426777-80493952-9a94-4bbc-b378-e2ab1215af53.jpg)
