### ISSUE TITLE
Make sure all docstrings are present and up to date 

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#158]
Check the docstring of each function for:
- Does it exist? If not create one or create a ticket for the person who created the function.
- Does it describe what the function does? (At least a one-liner for sub-functions, more in depth for more significant functions)
    - If it has a description, is it up to date?
- (for main functions and significant sub-functions) does it have the "arguments" and "returns" listed?  

This is related to #116 and is a dependency of #118

**Comment by paigeh1** [comment]
I have now created several issues stemming from this which details what parts of the code documentation need to be updated for each module. Once those issues have been resolved/further discussion has been made I will close this issue.

**Comment by nkshaw23** [comment]
@james-westwood I believe this can be closed.

**Comment by james-westwood** [comment]
Closed
