### ISSUE TITLE
SDG Data team questions

### ISSUE THREAD

**Issue by quartm** [ONSdigital/SDG_11.2.1#163]
-	It would be good to get some clarity on how disability status is defined and whether it is in line with the GSS harmonised disability criteria? As it doesn’t look like the disability status is in the typical “disabled”/”not disabled” format. It would also be helpful for me to get an understanding on how the disability breakdown is established at the local authority level.

-	To what extent does the data you’ve produced fit it or differ with the produced by the UN at the city level for various UK urban areas? https://data.unhabitat.org/datasets/GUO-UN-Habitat::11-2-1-percentage-access-to-public-transport/explore?showTable=true

-	In terms of geography, from reading the UN metadata the indicator seems to very specifically focus on urban areas (using the UN definition), whereas we seem to have departed from this to use local authorities as the main geography, I’m guessing this was intentional but would be good to get some background on this.

-	This may have also been discussed previously but was it deemed unattainable to disaggregate data for low capacity (buses) and high capacity (trains, metro, ferries) public transport?

**Comment by james-westwood** [comment]
Also mentioned by Max (in an internal email)

"The values are in the correct location but it looks like you need to swap the unit measure and multiplier around (e.g. unit measure = percentage (%), unit multiplier = units"

I have created a new issue to address this: https://github.com/ONSdigital/SDG_11.2.1/issues/179

**Comment by james-westwood** [comment]
After creating this milestone to correct the data according to this feedback, I am going to close this issue.
