### ISSUE TITLE
Check the England-Wales output data

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#164]
The output data for the first (ever) run for all local authorities in England and Wales. It took 2.5 hours to calculate (and I am fairly confident [this ticket ](https://github.com/ONSdigital/SDG_11.2.1/issues/159 )will help to speed things up and if not, [this issue ](https://github.com/ONSdigital/SDG_11.2.1/issues/165)will identify where bottlenecks lie). 

**We need to identify problems with the data and squish any bugs.**

- One problem I have spotted already is "Kingston upon Hull, City of" has no results. Need to investigate why this is. [Ticket for this issue](https://github.com/ONSdigital/SDG_11.2.1/issues/166). 

**The (preliminary, unchecked) Results**
[All_results.csv](https://github.com/ONSdigital/SDG_11.2.1/files/8061349/All_results.csv)

**Comment by jwestw** [comment]
This ticket is too generic. Problems have been identified via the data team review and my own initial review.
