### ISSUE TITLE
Create "non-disabled" data for every local authority

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#173]
Currently each LA has the data calculated for the number of people with disabilities, but not without disabilities. 

Previously this was understood (wrongly) to be included in all the other data, but these are totals for the other aggregates and disaggregations. 

Each LA needs the calculations for "non-disabled" while every other dimension is "Total" (blank).

**Comment by jwestw** [comment]
@Antonio-John  I am going to pick this up

**Comment by jwestw** [comment]
Notes on investigation:

I am going to work out if the columns add up with each other. 
    1) Does  "Day-to-day activities limited a lot" +   "Day-to-day activities limited a little" ==   'Day-to-day activities not limited' ?
    2) If not, do any or all of these add up to the total population for each OA?

- Creating a population df from the `la_pop_df` with `la_pop_only = la_pop_df[['OA11CD','pop_count']]`
- merging with `disab_with_total_pop = la_pop_only.merge(disability_df, on="OA11CD")`
- 

**Running inquiries:** 
- any(disability_df.iloc[:,1] + disability_df.iloc[:,2] == disability_df.iloc[:,3])
    - False
 So that means that none of the rows pass test (1)
-

**Comment by jwestw** [comment]
We now have a "non-disabled" column

![image](https://user-images.githubusercontent.com/67740306/159048267-e9ac7e25-96ee-43f6-9725-e42cae4aa1ac.png)

More changes need to be made so this comes through in the results.

**Comment by jwestw** [comment]
The non-disabled stats are now feeding through into the outputted csv

![image](https://user-images.githubusercontent.com/67740306/159260896-2def144e-23fa-40ed-8b5f-d51ff3c8eea4.png)

**Comment by jwestw** [comment]
We have been looking at the definitions of disability to make sure this calculation is consistent with GSS harmonized disability data. 

To understand the data, we looked at the questions and their possible responses in the [Measuring disability for the Equality Act 2010 harmonisation guidance](https://gss.civilservice.gov.uk/policy-store/measuring-disability-for-the-equality-act-2010/). 

| Question                                                                                                                      | Response options            |
|-------------------------------------------------------------------------------------------------------------------------------|-----------------------------|
| Do you have any physical or mental health conditions or illnesses lasting or expected to last 12 months or more?              | Yes / No                    |
| Does your condition or illness\do any of your conditions or illnesses reduce your ability to carry-out day-to-day activities? | Yes, a lot Yes, a little No |


People who will be considered "Non-disabled":
- Person who answers no to the first question
- Person who answers yes to the first question, but no to the second question. 

> "A person who says yes, they have physical or mental health condition(s) or illness(es) lasting or expected to last for 12 months or more, but it doesn’t restrict their activity are non-disabled."

Therefore the 
"Total people with disabilities" = "Day-to-day activities limited a lot" + "Day-to-day activities limited a little" 
or 
`disab_total = disab_ltd_little + disab_ltd_lot`

And the total 
"Non-disabled" = "Total Population" - "Total people with disabilities"
or
`non-disabled = pop_count - disab_total `

**Comment by jwestw** [comment]
I am happy with that the new non-disabled data is being calculated correctly. However the code is repetitive, so I will create a ticket to clean that up. 

https://github.com/ONSdigital/SDG_11.2.1/issues/187
