### ISSUE TITLE
Establish if disability data is in line with the GSS harmonised disability criteria

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#174]
Based on [feedback](https://github.com/ONSdigital/SDG_11.2.1/issues/163) from the SDG data team, we need to establish if our disability data is in line with the GSS harmonised disability criteria and clear up some other issues. 

@Musa-Chirikeni 
1) Do you know if the disability data, sourced from NOMIS QS303, is GSS harmonised? 
2) How is the disability breakdown is established at the local authority level.

**For the developer:**
- Explain what is the data available via QS303. 
   - What are the categories?
   - How are we aggregating it into “disabled”/”not disabled” format currently?
   - Check with [quartm](https://github.com/quartm) if this aggregation is acceptable.

**Comment by MusaChirikeni** [comment]
1. Do you know if the disability data, sourced from NOMIS QS303, is GSS harmonised?
- Nomis data is ONS data and should (to the best of our knowledge be harmonised)... 
- Worth checking with Census on this. Contact Lau Magro (Nomis Data Expert)
- Has the harmonisation changed from census to census?

2. How is the disability breakdown is established at the local authority level.
- Disability data is available at Output Area level and has been summarised to Local Authority level for this indicator. 
- The outputs are reported at both Urban and Rural 
- The stats for the indicator are reported at Local Authority level to allow for rural/urban outputs which takes into account all human settlements as stated in Goal 11

**Comment by jwestw** [comment]
The way the disabled and non-disabled data has been calculated is discussed here: https://github.com/ONSdigital/SDG_11.2.1/issues/173#issuecomment-1074955892
