### ISSUE TITLE
Develop a feature to consider transport capacity

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#176]
Bring consideration of transport capacity into the calculation. i.e. differentiate low capactiy buses vs. high capacity trains

**Comment by jwestw** [comment]
As mentioned in https://github.com/ONSdigital/SDG_11.2.1/issues/175#issuecomment-1051005221 I will refer to the method that was used by the EU to calculate data for the UN. 

The way they differentiate and label the stops is:
- low-capacity modes (e.g. bus, tram) 
- high-capacity modes (e.g. train, metro)

Steps:
- Output a csv before changing the code and back it up
- Find which codes in the NAPTAN guideance refer to bus, tram, train and metro respectively. 
- Map from the stoptype column to a new "Capacity" column according to the above mapping. 
- Apply the buffer points function according to Capactiy. i.e. low -> 500m and high -> 1000m
- Re-run the calculation, outputting a csv and compare.

**Comment by james-westwood** [comment]
@Antonio-John Thank you for picking this up. 

Check [this comment ](https://github.com/ONSdigital/SDG_11.2.1/issues/177#issuecomment-1044943964)for codes that we should see for the various trams, buses, trains etc. Then delineate capacity according to the comment above in the this issue.  

An approach is also outlined in the "Steps" above.

**Comment by james-westwood** [comment]
I have deleted and re-created the[ branch for 176 ](https://github.com/ONSdigital/SDG_11.2.1/tree/transp_capacity_%23176) because the other one had got into a bit of a mess (something to do with version control). 

I have made one change in 809de7285fd156a7985d547d43f8337224fba836 which now leads to the StopType being imported. 

![image](https://user-images.githubusercontent.com/49570694/161378666-9c80a48a-9b46-4e5f-9e82-84b7160137d0.png)


So you can categorize from here.

**Comment by Antonio-John** [comment]
Thanks for work so far. Have pulled this branch onto my local machine.

**Comment by Antonio-John** [comment]
![image](https://user-images.githubusercontent.com/74070596/162416696-ea201d2d-bca6-4ea9-867d-ac7380ef6b61.png)

**Comment by jwestw** [comment]
Follow up ticket to calculate higher capacity stops: https://github.com/ONSdigital/SDG_11.2.1/issues/196

**Comment by Antonio-John** [comment]
Unique values in current ```StopType``` are:
BCT
RSE
FTD
BCS
TMU
AIR
BCE
TXR
STR
BCQ
BST
RLY
RPL
GAT
FER
FBT
MET
PLT

**Comment by Antonio-John** [comment]
Filters dataframe based on if ```StopType``` is one of the following:

```["RSE","RLY","RPL","TMU","MET","PLT","BCE", "BST","BCQ", "BCS","BCT"]```

Creates new column called ```capacity_type``` based on high/low capacity with the following dictionary:

```{"RSE":"high",
  "RLY":"high",
  "RPL":"high",
  "TMU":"low",
  "MET":"low",
  "PLT":"low",
  "BCE":"low", 
  "BST":"low",
  "BCQ":"low", 
  "BCS":"low",
  "BCT":"low"}```

**Comment by Antonio-John** [comment]
![image](https://user-images.githubusercontent.com/74070596/164479204-ce32e60c-d00a-49e2-8d51-7831d59000b1.png)
