### ISSUE TITLE
Explore if we can disaggregate data for transport capacity

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#177]
@quartm asked:
"was it deemed unattainable to disaggregate data for low capacity (buses) and high capacity (trains, metro, ferries) public transport?"

This is a discussion. 

My thoughts on it are that:

- This may partially be covered by issue https://github.com/ONSdigital/SDG_11.2.1/issues/123 as this will take into account frequency. i.e. if a bus arrives once a week or once every hour - which is important. Currently this is in our project for version 1.2 https://github.com/ONSdigital/SDG_11.2.1/projects/5 but it can be put into https://github.com/ONSdigital/SDG_11.2.1/projects/1 if this is considered essential. Note: other countries (e.g. Estonia, and Sweden I think) have included transport frequency data into their calculations. 
- I am quite sure that transport capacity is not part of the calculation under the official methodology but I might have missed something there. Nonetheless, I think it will be an interesting addition, so:
    - I have created another ticket to [develop a feature to consider transport capacity](https://github.com/ONSdigital/SDG_11.2.1/issues/176).

**Comment by james-westwood** [comment]
@quartm This is a really good catch. I will got back to the data and have a look if we can label stops "high-capacity" or "low-capacity" - then run the distance analysis accordingly. I imagine this will push up the count of those who have access significantly. 

With regards to point a. above this would be really difficult to establish. I know there was a method for a very similar analysis suggested quite a while ago by the data science campus, which used Google streetmaps/streetview pictures and machine learning to analyse pictures of the stops. That sounded tricky and very experimental. Also, I just don't think the street view pictures are available like that any more. Obviously it depends on the disability, but things like ramps and lowering step buses are going to be relevant and some of that depends not on the stop but on the facilities on the transport itself. 

Again, for point c, I am very unsure how this would be established. We would need to know the criteria (I imagine things like good lighting and just generally being in an area with a lower-incidence of street crime) and get data for those. Again, some of that would be very difficult to get. 

With regards to point b. though, this will be solved by #123 

It's really useful to look at write-ups about how other countries calculated this indicator. 

 - [Estonia](https://www.efgs.info/11-2-1-estonia/)
 - [Sweden](https://www.efgs.info/11-2-1-sweden/)
 - [Poland](https://www.efgs.info/11-2-1-poland/)
 - [Portugal](https://www.efgs.info/11-2-1-portugal/)
 - [Austria](https://www.efgs.info/11-2-1-austria/)
 - [Norway](https://www.efgs.info/11-2-1-norway-test-page/)

I have read through Sweden's and Estonia's method and neither seem to have taken disability into account.

**Comment by jwestw** [comment]
Made a branch to implement this: https://github.com/ONSdigital/SDG_11.2.1/tree/transport_capaity_%23176
