### ISSUE TITLE
Investigate inactive stops in stops.csv

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#178]
Having re-looked at the stops.csv data recently, I noticed there is a column called **Status** which indicates if the stop is in use or not. 

![image](https://user-images.githubusercontent.com/49570694/155127952-b7041070-c99e-4bb4-b877-5670b7db95cc.png)

The possible entries are 
- "" (i.e. it's blank)
- "active"
- "inactive"
- "new"
- "pending"

In our current **stops_df** (22nd Feb, 2022, running from the master branch) does not contain this column, nor has it been filtered on this basis. 

![image](https://user-images.githubusercontent.com/49570694/155124116-46db05c0-dbfd-4b09-b832-0919a308605e.png)

So far it has proven difficult to find a definition of **Status** values. 

- [NaPTAN guide for data managers  ](https://www.gov.uk/government/publications/national-public-transport-access-node-schema/naptan-guide-for-data-managers) does not contain a defnition of the **Status** field.
- The document ["STOP STATUS IN NaPTAN AND DEALING WITH NaPTANs THAT ARE
NO LONGER REQUIRED"](http://naptan.dft.gov.uk/transxchange/ebsrnews/ebsr_03/Stop%20Status%20in%20NaPTAN.pdf) contains definitions of "active", "suspended" etc, but says they should be under "Stop Availability". Whereas the "Status" columns should have the values "ACT", "DEL" and "PEN". Also note that this document is marked as DRAFT. 

Overall the task is to remove stops that are not in use from the analysis. This probably means filtering out "inactive" and "pending" but for thoroughness we need to get definitions on the others. 

### Steps for the developer:

- email the [DfT NaPTAN team](mailto:Naptan.NPTG@dft.gov.uk) to enquire about:
    - If we are using the most recent data (our [current link](http://naptan.app.dft.gov.uk/DataRequest/Naptan.ashx?format=csv)), and if not, should we be using the [NAPTAN API](https://naptan.api.dft.gov.uk/swagger/index.html) for example? There is a new [Beta Site](https://beta-naptan.dft.gov.uk/) should we be downloading from that?
    - If we should use the API (could be better for us) can we have some documentation on it? 
    -  What the definitions of "active", "inactive" etc are. 
- Look at either our existing data (from the csv) or the new data they point you towards 
- Filter the dataframe to remove stops that are not in use. 

Bear in mind our stops data must have the longitude data and the latitude data.

**Comment by Antonio-John** [comment]
Hi, 

I work within the Office for National Statistics and am using NaPTAN data to conduct some analysis. I had a couple of queries about the data which I was hoping you could answer:

1)	The data we currently use is from the [NaPTAN ](https://beta-naptan.dft.gov.uk/)website. Is this the most recent data or should we be using the [NaPTAN api](https://naptan.api.dft.gov.uk/swagger/index.html)?

2)	If we should be using the API, is there any user guide or documentation that would be helpful for this?

3)	There is a column called Status within the stops data. I have looked at the [NaPTAN guide for data managers](https://www.gov.uk/government/publications/national-public-transport-access-node-schema/naptan-guide-for-data-managers) and couldn’t find a definition of the Status field. The unique entries in the Status field appear to be:

Possible Values
“”(i.e. it's blank)
"active"
"inactive"
"new"
"pending"

	Do you have a definition of what the values mean please? This will help us remove stops that are not in use from our analysis. 

Many thanks,

Antonio`

**Comment by Antonio-John** [comment]
draft email written. Would you mind taking a look to see if it's okay please? @james-westwood @Mark-Simons-ONS  Then can send after that

**Comment by james-westwood** [comment]
Except the formatting it all looks good.

**Comment by Antonio-John** [comment]
great, have sent email :)

**Comment by Antonio-John** [comment]
Hi Antonio, 

Thanks for the query, we have recently updated the website and created the API and they are both the same output – and they are always the most up to date output. 

We only have minimal documentation on the API page, but we are currently looking to add an expanded guide this year. 

This is currently the most relevant document for details guidance
[http://naptan.dft.gov.uk/naptan/schema/2.4/doc/NaPTANSchemaGuide-2.4-v0.57.pdf](https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fnaptan.dft.gov.uk%2Fnaptan%2Fschema%2F2.4%2Fdoc%2FNaPTANSchemaGuide-2.4-v0.57.pdf&data=04%7C01%7CAntonio.Felton%40ons.gov.uk%7C6514261c226e46691a1f08d9f77cddf0%7C078807bfce824688bce00d811684dc46%7C0%7C0%7C637812939129672280%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JHPPAdbz9g00dmXfxIZ9YNXiLW7kSN3qv0uE4tkd9bM%3D&reserved=0)
but it isn’t always obvious what things actually mean!

The best description of status is on p158 of this document. I don’t think “new” has been used anywhere. 

StopPoint and StopArea instances in the NaPTAN database may have one of three states, as indicated by the Status attribute: 
� ‘Active’: Stop is either in use or available to be used. 
� ‘Inactive’: Stop is in database but is marked as ‘inactive’ and is not currently in use or available for use. If the StopAvailability (see 6.5) has been used to transfer or suspend the stop for the period within which the data is published, the status of the stop must be ‘active’. This represents a change of interpretation with release 2.4 – and ensures that stops remain available for Bus Service Registration and other purposes whilst it is temporarily suspended or transferred. 
� ‘Pending’ delete: Stop is missing, or flagged as deleted from the most recent data upload, and may be in process of being made inactive. Will continue to be exported as if ‘active’ until status is clarified.

Let me know if this helps?

Regards

Adrian

**Comment by Antonio-John** [comment]
Couple of thoughts I had from this email. 
- Are we using the latest version of stops? We might have to pull from the API to ensure we are? Not sure if this is a yearly publication or how often the data get's updated. Might have to time stamp data to ensure analysis is reproducible. 
- Can definitely get rid of inactive stops. 
- Not sure about pending. I'm not sure what Adrian means by will continue to be exported as if active.

**Comment by jwestw** [comment]
I suggest going back and asking for those couple of points of clarification. 
1) How often is the data published? 
2) How can we tell when the data was updated (is there a time stamp or publication date?)
3) Could they explain what "exported as if active mean"? Can transport users catch transport from Pending stops or not?

**Comment by Antonio-John** [comment]
-Yesterday morning I went back and asked about how frequently the data is published. The answer is the timeframes of the data being published isn't consistent. Each LA uploads to the data when and if they need to. The link above shows when a LA last uploaded or changed something in the data. They say a lot of users upload every week or month but there is the potential that nothing has changed. 
-I will go back and ask about exported if active.

**Comment by Antonio-John** [comment]
Conversation between @Antonio-John & @james-westwood  25/02/2022
- Start to use the NaPTAN API to be able to download data. New ticket for this #183 
- Can drop inactive stops from stops.csv, waiting for confirmation how to deal with pending stops.

**Comment by Antonio-John** [comment]
-Treat stops without a status (i.e blank) as active.
-Treat stops that are pending as active as well. Only 11 stops like this in the live dataset as of the 1st March 15:00.

**Comment by jwestw** [comment]
This has been implemented by #186
