### ISSUE TITLE
Use NaPTAN API to get stops data

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#183]
Following from discussions in #178 the use of the API would be beneficial to get timely data into the project. 

**Steps for Developer**
-Add functionality to the pipeline to be able to download data from the [NapTAN API.](https://naptan.api.dft.gov.uk/swagger/index.html)
-Once downloaded the data needs to be time stamped.
-Pipeline needs to have the functionality so that if the latest version of the file downloaded is more then a month old then download another a newer version of the data using the API.

**Comment by Antonio-John** [comment]
My request library was throwing up a SSL error every time I requested something. This was used as a solution to the [problem](https://github.com/conda/conda/issues/8273).

**Comment by Antonio-John** [comment]
Lot of functionality in data_ingest.py I can use.

**Comment by jwestw** [comment]
Let me know if I can be of help with this.

**Comment by Antonio-John** [comment]
-Have added functionality to download straight from the API to the data folder whilst time stamping the data.
-Have added a function which gets the latest file stops date.
Next Steps
-Add a switch to only trigger the stops being downloaded when the latest stop date is older then 28 days.

**Comment by Antonio-John** [comment]
Skeleton main function might look something like this:
```
def get_stops_file(dir):

    today=datetime.now().strftime('%Y%m%d')
    latest_date=_get_latest_stop_file_date(dir)

    if today-latest_date>28:
        # read in latest feather file
    else:
        # download from the api and save this as a feather file

    return stops_df
```
