### ISSUE TITLE
Apply the `buffer_points` function to calculate 1km for high capacity stations

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#196]

**Comment by Antonio-John** [comment]
Used np.where to apply buffers.  Our check 
![image](https://user-images.githubusercontent.com/74070596/164699048-220807ca-d798-445d-b4cc-d27436d39499.png)

**Comment by james-westwood** [comment]
@Antonio-John @paigeh1 Great work. 

Do you remember we discussed previously that we might change the buffer distance if we ever got better information on how disability and age might affect walking distance. E.g. if we chose (and I am just picking example figures here) the buffer to for people 70-80 to be 250m and people 80+ to be 100m...

If you agree, maybe we can have a config setting to cover these potential changes later on. I know this was not in the original requirements and is therefore scope creep, but maybe we could have a config setting something like:

```yaml
high_cap_buffer = 1000
low_cap_buffer = 500
```

Happy to hear your opinions!

**Comment by paigeh1** [comment]
We agree with this so we have added in the high_cap_buffer and low_cap_buffer into the config file. 

We also loaded in config into the `geospatial_mods.py` because of the potential of additional buffers being added - we did not want to add several arguments into the function in the main script.
