### ISSUE TITLE
Improving docstrings in `data_ingest.py`  functions

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#197]
This links to improving code documentation in  https://github.com/ONSdigital/SDG_11.2.1/issues/158. I have separated this into certain parts of the documentation that could be improved or are currently missing. Some may be self explanatory (e.g. the arguments) that may not need documentation but I have put here in case.

Functions that need a docstring or updated documentation:

- [x] `_import_extract_delete_zip`
- [x] `_csv_to_df`
- [x] `capture_region`

Functions that may need an arguments section in docstring:

- [x] `get_shp_file_name`
- [x] `get_oa_la_file_name`
- [x] `_get_stops_from_api`
- [x] `_get_latest_stop_file_date`
- [x] `_save_latest_stops_as_feather`
- [x] `get_stops_file`
- [x] `get_whole_nation_pop_df`
- [x] `get_whole_nation_pop_df`
- [x] `_pd_to_feather`

Functions that may need returns:

- [x] `delete_junk`
- [x] `_extract_zip`
- [x] `_grab_zip`

**Comment by paigeh1** [comment]
I am looking to use the [Napoleon extension](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#module-sphinx.ext.napoleon) in Sphinx which requires code documentation to be in a certain style/format: either Google or NumPy. I think we mostly follow Google but can all functions be checked to ensure they follow this format?

Example of code documentation in Google format:

```
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Args:
        arg1 (int): Description of arg1
        arg2 (str): Description of arg2

    Returns:
        bool: Description of return value

    """
    return True
```

**Comment by nkshaw23** [comment]
Three functions marked as may need return statement all return nothing so not adding one.

**Comment by nkshaw23** [comment]
All functions checked as mentioned above - went through all functions and tried to make spacing / types / indentation etc consistent through docstrings.

A couple of points to raise:

1) in `_csv_to_df` the parameter `persistent_exists` defualts to `None` but think this should be `True` as the docstring states?

**Comment by nkshaw23** [comment]
Actioned the above so can now close issue.
