### ISSUE TITLE
Improving code documentation for functions in `ftp_get_files_logic.py`

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#200]
This links to improving code documentation in https://github.com/ONSdigital/SDG_11.2.1/issues/158.

The function `sub_get` requires:
- [ ] A couple typos being resolved
- [ ] A returns section here (e.g. saying it returns appended list)

The function `execute_file_grab` requires a docstring as well.

**Comment by jwestw** [comment]
We are not using FTP anymore so will delete this ticket
