### ISSUE TITLE
Improving code documentation for functions in `geospatial_mods.py`

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#201]
This links to improving code documentation in https://github.com/ONSdigital/SDG_11.2.1/issues/158 and can also be achieved alongside issue https://github.com/ONSdigital/SDG_11.2.1/issues/196.

The function `buffer_points` needs: 

- [ ]  an explanation of the arguments involved
- [ ]  a returns section (explaining the dataframe outputted)

**Comment by nkshaw23** [comment]
Reviewed with changes pushed to #197
