### ISSUE TITLE
Create total population row (served+unserved)

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#206]
Total (with blanks across all rows) for the local authority, is not being calculated. The needs to be caluculated and presented in the final df and csv.

**Comment by Antonio-John** [comment]
Have ran into this issue when processing Scotland data in #284 

This needs to be implemented for both the England & Wales Script and for Scotland. The changes could happen within one of the ```data_transform``` module.

**Comment by Antonio-John** [comment]
I'm going to start looking at this.

**Comment by Antonio-John** [comment]
Have gone into debugging mode through the script. 

I think it doesn't create this row because in ```reshape_for_output``` function in ```data_output``` when the melting occurs the variable ```total``` is both in the ```id_vars``` & ```value_vars``` arguments.

**Comment by Antonio-John** [comment]
Manual examples of what this should look like can be found in #188 

![image](https://user-images.githubusercontent.com/74070596/185622699-c49da4b6-3946-40a0-99db-89fcfde23f71.png)

**Comment by Antonio-John** [comment]
Have added in some extra code within the ```data_output``` function. 

Here are examples outputs for both the Eng&Wal and then Scotland outputs 

[All_results.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9382321/All_results.csv)

[Scotland_results.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9382322/Scotland_results.csv)
