### ISSUE TITLE
Computation of service areas

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#21]

**Comment by jwestw** [comment]
- Create euclidean buffer around the transport stops
 - combine the polygons created 
 - plot the polygons

**Comment by james-westwood** [comment]
The buffer function is working. Pushed in this commit https://github.com/james-westwood/SDG_11.2.1/commit/dd720361ca0b58f3858b9ed017c881cd5404c8e5

**Comment by james-westwood** [comment]
Trying to get the buffered stops to join up. Have tried .dissolve which uses Shapley's unary_union method in the background.

So just tried it with unary_union directly. This is the output. 

![image](https://user-images.githubusercontent.com/49570694/103351255-89aa7200-4a9a-11eb-9e5f-b963297c6ef2.png)

I think it would be better to niche down to a much smaller sub-section of B'ham and plot the stops (Points) and the service area (MULTIPOLYGON) to see the difference.

**Comment by james-westwood** [comment]
Although the dots on the plot above are polygons, I think they are much too small (though i don't know how to establish how big/small they are in km). I need help from Geospatial here. The polygons need to be 0.5km across.

**Comment by james-westwood** [comment]
Isolating a small sub section of Birmingham. Using a data set from [https://www.doogal.co.uk/](https://www.doogal.co.uk/) I am isolating the stops in Acocks Green, a ward of Birmingham. I am doing this to make calculations easier.

```python
# grab some coordinates for a little section of birmingham
ag_east_north = pd.read_csv('Acocks_Green_postcodes.csv', usecols=['Easting', 'Northing'])

eastings = [easting for easting in ag_east_north.Easting]
northings = [northing for northing in ag_east_north.Northing]
east_min = min(eastings)
east_max = max(eastings)
north_min = min(northings)
north_max = max(northings)

# limit the stops, filtering by the min/max eastings/northings for Acocks Green
north_mask = (north_min < birmingham_stops_geo_df['Northing']) & (birmingham_stops_geo_df['Northing'] < north_max)
east_mask = (east_min < birmingham_stops_geo_df['Easting']) & (birmingham_stops_geo_df['Easting'] < east_max)
# Filter the stops 
ag_stops_geo_df = birmingham_stops_geo_df[north_mask & east_mask]
```

![image](https://user-images.githubusercontent.com/49570694/103410817-fee27980-4b64-11eb-99e0-5ef754ac3ccf.png)


And plotting within Birmingham it's like this:

![image](https://user-images.githubusercontent.com/49570694/103410836-14f03a00-4b65-11eb-9675-74ac59ec9590.png)

**I feel like this is successfully calculating and plotting the service areas.**

**Comment by jwestw** [comment]
Closing this old issue as it was done long ago.
