### ISSUE TITLE
Create function to parse XML into dataframes for analysis

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#212]
We need to bring in the time table data which is in XML. This needs to be analysed and used to filter out stops that do not meet certain criteria. 

Possibly use https://docs.python.org/3/library/xml.etree.elementtree.html

A method here: https://towardsdatascience.com/extracting-information-from-xml-files-into-a-pandas-dataframe-11f32883ce45

**Comment by nkshaw23** [comment]
Closed by #257 which focused on parsing data in GTFS format instead.
