### ISSUE TITLE
Documentation: List of data to be described

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#213]
Taken from comment in  #156 

#### List of data to be described: 

- Stops/NAPTAN data
- Population data
  - OA data from census
  - OA data from population estimates
  - Population weighted centroids
  - The file used for OA to LA mapping

- Data should be described (size and shape of data, open source, what columns there are, availability and summary of what it is), URL given. 
   - description can be taken from the source (e.g. NAPTAN website)
- Possibly link to code which extracts the data, or refines it. 
    - Could link to the particular page/tab on our github hosted pages

**Comment by Antonio-John** [comment]
Started here - https://docs.google.com/document/d/1IEr9aWBKiHCS0M6RWcaQmpAych5AkaPiUhfTQ9hQ9iE/edit?usp=sharing

**Comment by Antonio-John** [comment]
Naptan Data  https://data.gov.uk/dataset/ff93ffc1-6656-47d8-9155-85ea0b8f2251/national-public-transport-access-nodes-naptan

**Comment by nkshaw23** [comment]
@james-westwood and @nkshaw23 to read and review. If happy, ticket can be closed.

**Comment by nkshaw23** [comment]
Couple of minor comments:

1) Could order the stops count table alphabetically, and either make the screenshot include all stop types (and their codes) or include extra column to state what the stop type code is.

2) Maybe worth adding what years data being used for population estimates and boundaries. Admin boundaries can change quite regularly so its always useful, as a user, to know what year is being used.

**Comment by Antonio-John** [comment]
Just seen these comments :)  thanks for providing them @nkshaw23. I have addressed 2). The estimates/boundaries have to match the calculation year e.g if we are calculating for 2019 the estimates/boundaries have to be the 2019 version.

I will probably add the counts to the table at the top of the page.

**Comment by Antonio-John** [comment]
Here is the data description one to review @james-westwood

**Comment by Antonio-John** [comment]
[NaPTAN](http://naptan.dft.gov.uk/naptan/schema/2.4/doc/NaPTANSchemaGuide-2.4-v0.57.pdf)

**Comment by Antonio-John** [comment]
Make sure to change the GSS disability data to GSS disability definition.

**Comment by Antonio-John** [comment]
thanks for reviews
