### ISSUE TITLE
Documentation: Data quality write up

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#214]
Taken from #156
### Data quality write up
- Is the data peer reviewed or not?
- Is the data open source?
- Strengths of the data and standards 
    - Link to any quality and methodology resources/standards that the data adheres to, e.g. [Code of Practice for Statistics](https://code.statisticsauthority.gov.uk/)
- Any limitations that we see in the data e.g.: 
    - Pop weighted centroids not being granular enough
    - Population estimates have not figures on disability, so we calculated them ourselves
    - NAPTAN data is only updated when Local Authorities are ready to provide the data. Could be out of date?
    - potentially not being comparable to other EU data because we are using national standards for categories like "urban" and "rural" and also our location data is based on OA (ONS standard), not EU standards.  (Maybe state the difference between the UK and EU standard, where definition differ)

**Comment by Antonio-John** [comment]
[public_transport.xlsx](https://github.com/ONSdigital/SDG_11.2.1/files/8956570/public_transport.xlsx)

**Comment by Antonio-John** [comment]
https://docs.google.com/document/d/13UYSXtyG3V8mJkR69fKxGyrFefU0tMSsPop3UDjPL28/edit?usp=sharing

**Comment by Antonio-John** [comment]
Hi @MusaChirikeni

I had a couple of questions about the geo data sources please.

- Are the OA population weighted centroids official statistics? 
- What method is used to calculate centroids? Is this a standard method across calculating centroids? Are there different method? 
- For the LA boundaries we used the BGC type. Is this the correct type to use? There seems to be a few different types.

Many thanks,

Antonio

**Comment by Antonio-John** [comment]
Here is the data quality document @nkshaw23 @james-westwood

**Comment by Antonio-John** [comment]
thanks @MusaChirikeni !

**Comment by nkshaw23** [comment]
@Antonio-John I cant view the doc as need access. Can review then.

**Comment by nkshaw23** [comment]
Reviewed and added one comment.

**Comment by Antonio-John** [comment]
thanks for review @nkshaw23
