### ISSUE TITLE
Randomise LA for calculation.

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#215]
Currently, we manually set the LA to a specific LA e.g. Hull or North Devon to perform the calculations. It would be good if there is some sort of randomiser to choose the LA, as this might help test and potentially spot if there are any errors associated with the calculation. Steps for developer
- Introduce a random number generator - https://www.educba.com/random-number-generator-in-python/
- Get a list of all possible LA's
- Generate a random number n from 0, to how many LA's there are.
- Choose the nth LA in the list
- assign this nth LA to ```list_local_auth``` 

Note:
In time and when handing code over to SDG team, this will need to be commented out as the script will potentially need to perform the calculations for all LA's in one go.

**Comment by jwestw** [comment]
The steps for generating the number and choosing the nth index can be compressed into one step using `random.choice()`

**Comment by Antonio-John** [comment]
Have put in a merge request using ```random.choice()```
