### ISSUE TITLE
Write up Calculation Methodology section

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#221]
Links to issue #156. 

### Notes on Methodology

- Network/path calculation (not done, how it would be done, potential limitations and improvements)
- Calculation process
 - Geocoding the population data
     - ONS's method for doing this - census methods can be linked to
     - How many geocodes (centroids) there are
     - **MAIN METHOD**: Joining the OA population data with the OA population weighted centroid table (which contains location data - need to check this)
- Delimitation of urban areas:
    - Joining pop table onto urban rural OA table
    - ONS's method for doing this - link to method/description of how urban/rural is decided
- Computation of service areas
    - buffer method using Euclidean distance/radius to create polygon
- Calculation of population within service areas
    - Counting population centres within the service area polygons
    - How we calculate the buffer
- Disaggregations:
   - How we classify disability - use the write up here: https://github.com/ONSdigital/SDG_11.2.1/issues/173#issuecomment-1074955892
   - How we chose the age bins - 
   - Filtering dataframes according to demographic data available on age, sex and (estimates) disability status. 
- Aggregating up to LA level:
   - How results are combined to create output for the [data platform ](https://sdgdata.gov.uk/)

**Comment by james-westwood** [comment]
Work on this write up so far: https://docs.google.com/document/d/13Jt5zu1Pieqbg8DRHgWsAjhaHxsJCUsRXuCU70nYlIs/edit?usp=sharing

**Comment by jwestw** [comment]
Comparing UK measures to UN measures of disability. https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/disability/datasets/measuringdisabilitycomparingapproaches

**Comment by jwestw** [comment]
@nkshaw23 and @Antonio-John have looked at this and I have finished it. Happy to close this ticket. Ready to translate to markdown.
