### ISSUE TITLE
Review `requirements.txt` to remove/update redundant packages

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#225]
The  `requirements.txt` will require updating or removing as there are some packages mentioned e.g. `gptables` that are no longer used in the code.

The purpose of this ticket is to review all packages in `requirements.txt` and determine whether they are currently used in the code and, if not, they should be removed from the txt file.

**Comment by jwestw** [comment]
This seems to be a duplicate so I will close it. See https://github.com/ONSdigital/SDG_11.2.1/issues/203#issuecomment-1165610019

I have captured the above text.
