### ISSUE TITLE
Update and improve the process diagram

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#227]
The process diagram which is currently in the README is a low quality image and is somewhat out of date and incorrect in a few places. 

- We do not use SQL
- There is no OA to OA population weighted centroid step
- The urban/rural demarcation step is possibly in the wrong place.
- The disaggregation steps could do with being explained/illustrated a bit better.

**Comment by nkshaw23** [comment]
First draft with new format attached. Based on original flowchart, #221 and looking through `_main` module.

Points to note:
-  EU / Eng/Wales / Scotland definition of Urban / Rural areas needs to be added. Unsure about where this is in the code?
-  The service area buffer is created within the loop, but is displayed before this in the flowchart (like the original). Do we want to move this stage into the loop process?

Created using Gliffy (drag and drop - available through confluence) so change to layour and formatting are very easy to undertake.

![SDG_POC](https://user-images.githubusercontent.com/20166290/170707413-80735afb-8e6c-4b59-9e1f-ba51da6f9fa0.png)

**Comment by nkshaw23** [comment]
Comments below:

- Should "highly serviced stops" be a dataset (pink)?
Its down as grey as its a dataset yet to be created.
- "Compute proportion of population within service areas within LA" - we could drop "within LA" here.
Done
- Drop all intermediate FTP/CSV data outputs
Done
- Local Authority Boundaries are actually used to filter the stops (and I think the OAs) to make the calculations in each loop. How could we reflect this?
There is the 'LOOP: For each LA in the top LH corner of the grey 'loop' process box. Is this not clear enough? Updated incase better.
- The pink "Pub transport stops" could have the word "geolocated" in it maybe?
Agree - added
- The "Compute service areas" and "Euclidean buffer" could be combined as they are one process. Same goes for the "Compute Service areas" and the "Paths and network calculation" I think.
Yep. I was trying to show that there were two different options buffer vs create network, but it is slightly confusing. Updated.
- Similar comment for the "Disaggregate data by" and the underlying categories. Could they be combined to show each is one process?
Changed.

![SDG_POC (1)](https://user-images.githubusercontent.com/20166290/174848423-bcf2f224-3b70-497b-9882-3a9c0810fe72.png)

**Comment by nkshaw23** [comment]
05km vs 1km buffer added

![SDG_POC (2)](https://user-images.githubusercontent.com/20166290/176874826-2c75b4d2-ee9a-4cd6-9bf1-bfadb6c88ed2.png)

**Comment by jwestw** [comment]
@nkshaw23 Sorry but we have realised that the urban/rural split is not actually a disaggregation. Could you take that out please? Call me to discuss.

**Comment by nkshaw23** [comment]
@james-westwood updated

![SDG_POC (3)](https://user-images.githubusercontent.com/20166290/176890685-2cf72ad3-20ea-49d9-a3a5-caf946bfcffb.png)

**Comment by jwestw** [comment]
> @james-westwood updated
> 


Perfect!

**Comment by Antonio-John** [comment]
-We need to add an extra step between disaggregation & share of population with convenient access to public transport.
-This step would reflect how we count up the OA's to get our LA calculation.

**Comment by Antonio-John** [comment]
Change for loop LA box to reflect:
- Filter OA's by LA.
- Filter stops by LA
- Aggregate results to LA level.

**Comment by nkshaw23** [comment]
Made some changes based on comment above.

- Specified that `population and rural/urban` data is calculated for each output area
- Added stages in for loop to for filtering to output areas in LA and then output areas in Stops (and changed connecting lines)
- Added aggregation step at bottom of loop.

![SDG_POC (6)](https://user-images.githubusercontent.com/20166290/179212210-22a49e35-5a62-4bc8-b5f3-0042a7e3714e.png)

**Comment by jwestw** [comment]
I think the improvement of this diagram is finished for now. So we can close this ticket. #254 will bring the diagram into the Sphinx pages.
