### ISSUE TITLE
Run availability analysis on Grimsby area - NE Lincolnshire

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#229]
- Output a csv as a deliverable to the DSC team
- Sense check the results before delivering

**Comment by paigeh1** [comment]
This has now been run and been sent across to @jwestw . Won't close this ticket until DSC are happy with the output.

**Comment by paigeh1** [comment]
@jwestw did we hear anything back from them? Are you happy for me to close this ticket?

**Comment by james-westwood** [comment]
Yes we can. :)
