### ISSUE TITLE
Add latest process diagram into sphinx docs

### ISSUE THREAD

**Issue by nkshaw23** [ONSdigital/SDG_11.2.1#254]
Once the latest process diagram has been finalised ( #227) then add into the sphinx docs.

**Comment by paigeh1** [comment]
@jwestw do we want the old diagrams deleted? I think they would be good to keep just in case? Let me know what you think.

**Comment by paigeh1** [comment]
![image](https://user-images.githubusercontent.com/102051068/182322886-52e6418a-d34e-4d89-9c97-971fc52f689d.png)

Working as expected, going to make pull request. Previous diagrams are still in the img_readme
