### ISSUE TITLE
Explore train/rail time table APIs

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#256]
There are two data sources that seem to have Rail Time table data for the UK, Atoc and Atoc Crsp. Starting with Atoc, explore what data is available and how to parse it. 

**Create accounts at:**

- https://data.atoc.org/user/register
- https://dtdportal.atocrsp.org/

The ATOC.CIF contains various file formats. Edward Jackson from DSC has written a parser to parse one of those files into a dataframe. Rather than re-inventing the wheel, we should keep an eye on their project to see if DSC will open source the code or even better the parsed data. 

In the mean time we can explore these sources and bus timetable data

**Comment by paigeh1** [comment]
https://data.atoc.org/sites/all/themes/atoc/files/RSPS5046.pdf information on the rail timetable data. Will look further into it

**Comment by jwestw** [comment]
I have accounts on both sites above. 

The data from data.atoc.org is a zip file containing the following files

Screenshot from 2022-08-11 14-34-50

I do not recognize the formats. I had a look inside the .mca file and it looks parsable with some effort. 

I am currently waiting for authorisation to be granted to see the data on dtdportal.atocrsp.org/

**Comment by jwestw** [comment]
I have parsed both the station codes csv from National Rail and the [Station locations json](https://github.com/ellcom/UK-Train-Station-Locations/blob/master/uk-train-stations-dictonary.json) into dataframes. They have a size mismatch but they are close. 

The National Rail station codes number: 2580
The Codes from the locations json number: 2595

**Comment by jwestw** [comment]
[stop_codes.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9310298/stop_codes.csv) This is the data I parsed from National Rail. It was previously in three columns

**Comment by jwestw** [comment]
There is an API for Open Rail Data: https://opendata.nationalrail.co.uk/
Not sure what info the API can serve

**Comment by jwestw** [comment]
After importing both the station code data set and the station I have found which stations are missing from each. This is based on set operations of the station codes in each data set. 

That means a station could be in both data sets but have different station codes. 

An example is Oxford. In the locations data set it is called "Oxford Parkway Rail Station" and has the code "OPY" but in the codes dataset it is called "Oxford Parkway" and has the code "OXP" (which is correct).

All of those that I checked in my `not_in_codes_df` have the wrong station code, when checked on nationalrail.co.uk e.g. https://www.nationalrail.co.uk/stations_destinations/OXP.aspx

- there are 34 stations in the locations dataset which are not found in the station codes dataset 
- there are 18 stations which are in the codes data set but not in the locations

Steps:
Correct the codes in the 34 stations in the locations dataset. This could be done programmatically but it would probably take longer than the changes to be manually carried out   
Some of the 18 in the codes dataset will then be matched once the codes in the locations data set are corrected, so re-run the set operations. 
With whatever number is remaining, check that all of them are in the UK. Validate them with a web search and get their location manually. 

Output an updated locations dataset with the correct station codes. Choose the names from the codes dataset because they aggree with Nationalrail.co.uk

**Comment by jwestw** [comment]
Exploring what is in the locations dataframe but not in the station codes dataframe, I have found a few examples of stations have a "lower level" listed. They have another (presumably upper level) station on the same site:

Examples are:
- Glasgow Central Low Level Rail Station and Glasgow Central Rail Station
- Glasgow Queen Street Low Level Rail Station and Glasgow Queen Street Rail Station

From Google maps, you can see the two station's location are not far and are on the same site. 

![image](https://user-images.githubusercontent.com/67740306/185389248-6ccf7397-47cb-4676-b70d-b5b4f79672d6.png)


I will include both in the station codes.

**Comment by jwestw** [comment]
Heathrow appears more times in the locations df than the station codes 

![image](https://user-images.githubusercontent.com/67740306/185391700-d1087378-855d-45a1-b3c1-3c9df5d96deb.png)


But "HTR" is missing from the station codes. I have verified this on https://www.nationalrail.co.uk too. 

![image](https://user-images.githubusercontent.com/67740306/185391386-b4e14fe1-3c0a-45c0-84b7-035aeee0d467.png)


Mapping the location of "HTR" 


![image](https://user-images.githubusercontent.com/67740306/185392127-0ba8f54b-6a60-40f5-ba63-db85a58530a3.png)

I am pretty confident this is a bus station. Therefore I am deleting it from the station locations df.

**Comment by jwestw** [comment]
Minffordd Ffestiniog will be removed. It's a narrow gauge rail station according to https://en.wikipedia.org/wiki/Minffordd_railway_station

![image](https://user-images.githubusercontent.com/67740306/185401370-f3186beb-2851-4143-96b8-94cc798e0225.png)

Minffordd (MFF) is present in both datasets

![image](https://user-images.githubusercontent.com/67740306/185401671-4e30642c-21aa-4b20-ae48-e915f8e8ea9d.png)


Deleting MFD from locations

**Comment by jwestw** [comment]
NTB Norton Bridge is present in the Locations df but not the station codes.

https://www.nationalrail.co.uk/stations_destinations/NTB.aspx shows it has been closed since 2017

![image](https://user-images.githubusercontent.com/67740306/185402112-934cea59-10c2-4345-a9e5-0c6cadd88f78.png)

NTB will be removed from locations.

**Comment by jwestw** [comment]
London St Pancras International LL Rail Station (SPL) is not matching. It's present in the locations but not in the codes. 

There are two St Pancras 

![image](https://user-images.githubusercontent.com/67740306/185405827-2ea2cd30-94b7-4f00-a3ba-dccfb4e5a410.png)


Have checked Google maps and am happy that they are on the same site. 

Deleting SPL

**Comment by jwestw** [comment]
Southease - Piddinghoe Road (ZBU) is not matching. Present in locations but not in station codes. It's not found on nationalrail.org nor on Wikipedia. The lat lon when mapped points to Southease village. 

![image](https://user-images.githubusercontent.com/67740306/185408627-b4f7ee8f-a4be-4c7b-9b7e-0d80d04e84ee.png)


The distance between mapped on Google maps:

![image](https://user-images.githubusercontent.com/67740306/185408965-6fca1e7c-cdce-4c28-9185-570fc2e162dc.png)

Pretty sure this is just pointing to bus stops, here mapped at: https://rail.traveluk.info/index.php/station-finder/map?atcocode=9100SESABUS

![image](https://user-images.githubusercontent.com/67740306/185409366-664d36be-af3e-4e5e-b895-e1f866ada177.png)

I will delete ZBU

**Comment by jwestw** [comment]
Removing AGR

![image](https://user-images.githubusercontent.com/67740306/185410623-aa505493-ff68-4fa5-84b5-bbb567c5773a.png)

**Comment by jwestw** [comment]
The result of my investigations in a csv 

[Uploading corrections_locations_not_in_codes.csv…]()

**Comment by jwestw** [comment]
Note: TIPLOC codes may be embedded within ATCO_Code (in NAPTAN data)

**Comment by jwestw** [comment]
Updated correction:

[corretions_stations_not_in_locs.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9381139/corretions_stations_not_in_locs.csv)

**Comment by jwestw** [comment]
Updated corrections:

[corrections_stations_not_in_locs.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9381171/corrections_stations_not_in_locs.csv)

**Comment by nkshaw23** [comment]
Basic data structure if we end up writing a parser ourselves. The [technical documentation](https://www.raildeliverygroup.com/files/Publications/services/rsp/RSPS5046_timetable_information_data_feed_interface_specification.pdf) is really good.

Only need two files (`.msn` and `.mca`). Within `.mca` lots of rows we can ignore for the time being.

Things to investigate further:
- `TI`, `TA` and `TD` records in `.mca`
- Daily updates dataset

![CIF data structure](https://user-images.githubusercontent.com/20166290/185616233-fe8fbaf3-9b8b-445b-89bc-2d632cb0cef4.png)

**Comment by nkshaw23** [comment]
Parsed `.msn` file of master station names. Location data is actually a grid reference - not an easting and northing - so alot harder to plot. Especially as they dont provide the 100km code (2 letters at the beginning). So we will need to use @james-westwood James resources for station coordinates.

The `'msn` file contains 3202 row for stations with a `tiploc_code` and a `crs_code` (3 letters). `tiploc_code` is unique for the stations but `crs_code` is not (186 duplicates, leaving 3016 records). See screenshot below for example of Upminster which has two stations with same `crs_code` and `grid_ref`.

![image](https://user-images.githubusercontent.com/20166290/186108089-66fcaa1b-9515-497b-9d88-2b4cc95eceae.png)

However the station locations json only contains 2595 (before @james-westwood cleaning above). The stations that dont have coordinates are [here](https://github.com/ONSdigital/SDG_11.2.1/files/9400684/no_coords.csv).

This raises a few points:

1) I think we should remove the duplicate entries in `.msn`
2) Need to think about what to do with stations that dont have coordinates.  Looks like a fair few are bus stations, undergrounds, trams etc but havn't looked properly yet. Found another [resource](https://transitfeeds.com/p/association-of-train-operating-companies/284) with creates GTFS files which obviously use the ATOC data and CIF format. In this file there are 2582 stations with coordinates, with roughly matches the values we currently have.

**Comment by jwestw** [comment]
The diagram is excellent! Makes everything very clear. 

> So we will need to use @james-westwood resources for station coordinates.

Glad to hear it will be of use. Also, can you give me a link to the person who plotted the train stations and posted the result on Twitter?

I think we could look to make two separate assets public:
1) Your parser code. (Which might be worth releasing as a package)
2) My stations location data. - Maybe we could link to TIPLOC codes too?

> The stations that dont have coordinates are [here](https://github.com/ONSdigital/SDG_11.2.1/files/9400684/no_coords.csv).

I worked through some stations (which I had names and 3-alpha codes for, from National Rail) but which I didn't have locations for. There were various reasons for them not having locations. One was a Eurostart station for example, another a historic station. 

There were more the other way round though, i.e. I had locations for them, but they didn't appear in National Rail's station codes dataset. They were mostly heritage stations, metro stations, or had the wrong 3-alpha codes.

**Comment by nkshaw23** [comment]
@james-westwood I have started a new ticket looking at implementing what is dicussed here (#294). Is it worth closing this now?
