### ISSUE TITLE
Produce Whole SDG Pop Estimates for Scotland 

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#261]
This involves producing the same calculation for England & Wales in the SDG script for Scotland. 

Steps for Developer:
- To produce an estimate for Scotland (without disaggregation's) 
- Include these data sources:
-- Scottish Usual Resident Population. 
-- Population Weighted Centroids.
--OA to LA look up

**Comment by Antonio-John** [comment]
Steps to be able to run Scottish Data:
You'll need a few extra files, I'll detail which ones and where to save them here.

Scottish Usual Resident Population. This is the population per output area from the 2011 census. [KS101SC.csv](https://github.com/ONSdigital/SDG_11.2.1/files/9214008/KS101SC.csv) Needs to be placed in data/
Population weighted centroids are found [here ](https://www.spatialdata.gov.scot/geonetwork/srv/api/records/9d977a73-7884-4870-ae76-afccf8e6fae8)they need to be placed in data/pop_weighted_centroids/scotland/2011/
[OA to LA lookup](https://geoportal.statistics.gov.uk/datasets/ons::postcode-to-output-area-to-lower-layer-super-output-area-to-middle-layer-super-output-area-to-local-authority-district-november-2021-lookup-in-the-uk/about) needs to be placed in data/oa_la_mapping/scotland/2021

**Comment by paigeh1** [comment]
To access the population weighted centroids, click "Access Portal" on the side.

You will then need to click the link as shown in the screenshot below:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/102051068/183630789-7cab6642-0043-42c8-8d5c-bba05d244d3c.png)

And then click on "2011 Output Area - Population Weighted Centroids" as shown in the screenshot below.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/102051068/183631335-b0040ccd-7340-4e29-9e5b-2eac7a5ae1f4.png)

This should download a zip file and then extract and place the data in data/pop_weighted_centroids/scotland/2011/
