### ISSUE TITLE
Produce Whole SDG Pop Estimates for Scotland by sex

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#263]
This is to produce estimates based on Male/Female split.
Steps for Developer:
- The data for Male/Female on an output area is contained with the Scottish Usual Population file already read in.
- Apply these disaggregation in a similar way to the way the SDG England & Wales script performs this.

**Comment by paigeh1** [comment]
I'll look into this one Antonio - assigned myself.

**Comment by paigeh1** [comment]
Have put in some code to add in sex. Currently an issue with female and male values being incorrect in the dataset (they don't add up correctly). I'm going to look at this early next week (w/c 15th August).
