### ISSUE TITLE
Produce Whole SDG Pop Estimates for Scotland by disability status.

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#264]
Steps for Developer:
- Source disability data for Scotland on an ONS basis. I suspect this will be the 2011 census results.
- Assess if this consistent with the GSS harmonised status of disability. 
- Merge this in into the Scottish data.
- Apply this disaggregation to the data, much in the same way it happens in the England & Wales Script

**Comment by paigeh1** [comment]
Found data for all output areas in Scotland [here](https://www.nomisweb.co.uk/census/2011/qs303uk). Using the 2011 census estimates, with output areas in 2011 for Scotland. To download the data, "output areas in 2011 in Scotland" will need to be chosen. This is to then be stored in data/ and renamed as QS303_scotland.csv

As this is the same data as used by @jwestw for England and Wales, the same logic will apply to decide who is classified as "disabled" and "non-disabled".


Attached an initial look at the dataset. 

![image](https://user-images.githubusercontent.com/102051068/185627897-af6fde11-e237-4f7f-a906-ab1cddac19bd.png)
