### ISSUE TITLE
Implement Data Documents into Sphinx

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#266]
There are two data documents called [data description](https://github.com/ONSdigital/SDG_11.2.1/issues/213) and [data quality.](https://github.com/ONSdigital/SDG_11.2.1/issues/214)

These have been reviewed and finalised but would be good to add to the Sphinx documentation.

**Comment by Antonio-John** [comment]
- @Antonio-John to create markdown files using google doc to markdown converter and place in docs/source/
- @paigeh1 & @Antonio-John to go through how to add these into the Sphinx documents.

**Comment by Antonio-John** [comment]
- Have used this converter - https://googledocstomarkdown.com

**Comment by Antonio-John** [comment]
Don't use converter above. Went through with @paigeh1 how to create the documentation with Sphinx. The main steps are:
1) Add markdown files to doc/source that you want.
2) Run ```sphinx-build -b html docs/source docs/html``` This will convert the markdown files to HTML.
3) Make sure you are happy with them by clinking on the html link. Can be viewed in a web browser. (Probably some VScode extensions to do this also)
4) Push to remote, then ask admin to change the page views to the branch you want, for it to be eventually merged in

**Comment by jwestw** [comment]
A slightly more formal version of the instructions above would be a great addition to the documentation

**Comment by Antonio-John** [comment]
Hey @nkshaw23 

@paigeh1 & I noticed that ```doc/html``` was included in the ```.gitignore``` This was preventing us staging changes to push to the remote repo. We have commented this out in the ```.gitignore``` and committed this version of ```.gitignore``` on the branch 266-implement-data-documents-into-sphinx associated with the ticket.

Was there any reason why this was included in the .gitignore & can we omit this line?

Antonio

**Comment by nkshaw23** [comment]
No - I was having trouble with `.gitignore` when working on this so must be a mistake that is left over.

I didnt realise that would cause issues with pushing changes to the remote - we have re-created the docs (thereby editing HTML files) and pushed up to a branch a few times over the last couple of weeks.

Unless I am misunderstanding (highly likely)...
