### ISSUE TITLE
Add method of calculating population of people with disabilities

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#267]
The method write up is missing how the year-on-year growth in the population of people with disabilities is calculated using from census-year data.

**Comment by james-westwood** [comment]
This is definitely covered in:
- [Disability status](https://github.com/ONSdigital/SDG_11.2.1/blob/master/docs/source/write_up.md#disability-status)
- [Considerations on disability status ](https://github.com/ONSdigital/SDG_11.2.1/blob/master/docs/source/write_up.md#considerations-on-disability-status)
