### ISSUE TITLE
filter bus timetable dataframe for a certain date

### ISSUE THREAD

**Issue by nkshaw23** [ONSdigital/SDG_11.2.1#279]
Create a function that filters the linked dataframe created in #278 for a user specified date.

**Comment by jwestw** [comment]
## Requirements:
- print out the number of bus services that were included to establish the highly serviced stops count
- Make a function to filter dataset by `day`
- put filter condition `day` in the config

The function selects the day selected from the valid date range in the timetable dataset - hence avoiding the problem of invalid dates input by the user. 

**There function that might be useful to build from:**

https://github.com/ONSdigital/SDG_11.2.1/blob/ab0c33c61d8ec516d78c88314175d261c465acbd/data_transform.py#L294

**Comment by james-westwood** [comment]
I branched from https://github.com/ONSdigital/SDG_11.2.1/tree/283-clean-bus-data to make https://github.com/ONSdigital/SDG_11.2.1/tree/279-filter-bus

**Comment by james-westwood** [comment]
Almost got this done, but filter not working and returning an empty df.

Troubleshoot here:

https://github.com/ONSdigital/SDG_11.2.1/blob/45ad2a201c49a72e117d430a1df3e6beff7bdea4/data_transform.py#L378-L381

Additional problem:
- I am not sure how to meet requirement "print out the number of bus services that were included to establish the highly serviced stops count" currently, as the filtered df doesn't have service numbers

**Comment by nkshaw23** [comment]
I haven't properly looked at / run code but could be due to a mistmatch in date format. Start date is in `%Y%m%d` but `filter_by_year` is in %Y-%m-%d`

`calendar_df['start_date'] = pd.to_datetime(calendar_df['start_date'], format='%Y%m%d')`
`start_year = f'{year}-01-01'`

**Comment by nkshaw23** [comment]
RE requirement 'print number of bus services' - all we want is just a count of the dataframe after filtering by day. e.g.

`There will be xxx,xxx stops by buses included in the analysis`

**Comment by jwestw** [comment]
![time_filter_conditions](https://user-images.githubusercontent.com/67740306/190660575-055cdc3c-3549-4900-803a-f5fd58273c18.jpg)

This is my logic to include services that run on the days that the user has selected. 

This diagram should be included in the documentation

**Comment by nkshaw23** [comment]
Closed by #327
