### ISSUE TITLE
Source 2011 LA Boundaries Scotland

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#285]
As we only have 2011 population data at an output area for Scotland. We should only use Scotland 2011 boundaries.

Steps for Developer:
- Find 2011 Scotland LA boundaries.
- Pass them into the script and ensure these are used through out the script.

**Comment by Antonio-John** [comment]
UK Boundaries - https://statistics.ukdataservice.ac.uk/dataset/2011-census-geography-boundaries-local-authorities

**Comment by MusaChirikeni** [comment]
Hi @Antonio-John 

You're right, The portal only has EW2011 version for the LAD boundaries. And yes the UK Data Service is a good option for sourcing historical boundaries which do not exist on the Portal. The link shows the clipped version of the 2011 boundaries. I would use the non-clipped version instead (available here)[https://statistics.ukdataservice.ac.uk/dataset/2011-census-geography-boundaries-local-authorities/resource/b5e4b25c-04c3-41f2-ac1f]. 

Apologies for the late response.

best regards,

Musa

**Comment by Antonio-John** [comment]
https://statistics.ukdataservice.ac.uk/dataset/2011-census-geography-boundaries-local-authorities

**Comment by Antonio-John** [comment]
Have had to find a different OA to LA lookup. The previous lookup was OA2011 to LAD21NM but I now want OA2011 to LAD2011. I haven't been able to find this. Musa is of till the 27th Jan so have emailed the geospatial department at ONS.

**Comment by paigeh1** [comment]
I think this is what the requirements of the ticket are:

- [ ] Download the LA 2011 boundaries for Scotland with the link Antonio linked above.
- [ ] Use a different OA to LA lookup which is linked in the draft PR

This data should give us what we need to complete the ticket

**Comment by paigeh1** [comment]
Hi @MusaChirikeni 

I am taking over this work from Antonio as Antonio has now left ONS and trying to get to grips with this ticket. I think Antonio asked about an OA to LA lookup for 2011 boundaries. So we want Scotland OA2011 to be mapped to LAD2011 codes. You, or someone on your team sent through this: https://www.nrscotland.gov.uk/files//geography/2011-census/OA11_to_SettLoc12.xlsx . I can't seem to find the correct OA to LA mapping in this file that I need as I thought Scotland LA codes were S120000XX codes. 

Does this mapping exist? Any help with this would be great :)

Thanks,
Paige

**Comment by paigeh1** [comment]
Thank you @MusaChirikeni for your input!

I think we are going to continue using LA2021 boundaries as we have a lookup for this. We would like to do some analysis geospatially to determine the difference between LA2011 and LA2021 boundaries.

**Comment by paigeh1** [comment]
Closing this ticket as we are doing geospatial analysis as mentioned in #427 . Might look at it at a later date
