### ISSUE TITLE
Source and Read in NI Population Data

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#288]
Steps for Developer:
- Source population data for Census 2011 based on Output Area. These are called Small Areas in NI.
- Source population estimates for Small Areas - these are the years in between the census.
- Read these data sources in.

**Comment by paigeh1** [comment]
https://www.ninis2.nisra.gov.uk/public/SearchResults.aspx?sk=KS101NI; Found some data here which I am going to store in data/. Will look to reading it in SDG_NI.py.

**Comment by paigeh1** [comment]
Data has now been read in.

@Antonio-John are population data and population estimates the same? I have read in the population data for small areas in NI into the script. I thought as there was little cleaning, there was no point in creating a function in `data_ingest` so this has just been done in the main script. I'm happy to hear your thoughts on this :)

**Comment by Antonio-John** [comment]
Big apologies for slow reply on this comment @paigeh1 . The population data refers to the Census data e.g 2001, 2011 and eventually 2021. The population estimates are just estimates between years the ONS/NISRA might produce/calculate.

**Comment by paigeh1** [comment]
Thanks for the reply Antonio. I've found [population mid-year esimates](https://www.nisra.gov.uk/publications/2020-mid-year-population-estimates-small-areas) for all small areas from 2001-2020 and have added this into Sync. 

Not sure if it is useful for future issues, but here is a [link](https://www.nisra.gov.uk/publications/2020-mid-year-population-estimates-northern-ireland) for local district population estimates on age and sex as well.
