### ISSUE TITLE
Get latest file name from atoc website

### ISSUE THREAD

**Issue by nkshaw23** [ONSdigital/SDG_11.2.1#292]
The name of the zip file we want to download changes each time it is updated. So we have to scrape the [atoc website](https://data.atoc.org/data-download) to get the either the filename, or the address.

![image](https://user-images.githubusercontent.com/20166290/186901819-549e5203-8075-4c94-9d4c-929f920546aa.png)

**Comment by nkshaw23** [comment]
I can view the [source page html](view-source:https://data.atoc.org/data-download) using requests but I need to be logged in to get the filename. Cant get this to work at the moment.

This is what we want to extract

![Capture](https://user-images.githubusercontent.com/20166290/186911623-f96ff72d-931d-4f26-8c88-794c7bb0404c.PNG)

**Comment by james-westwood** [comment]
@nkshaw23 I am going to have an exploratory look at this. Do you have any code already?

**Comment by james-westwood** [comment]
Branch created: https://github.com/ONSdigital/SDG_11.2.1/tree/292-get-latest-atoc

**Comment by james-westwood** [comment]
I am having big problems with the Atoc website. I can't even log into it using a browser, so I can't inspect what's happening. 

I have tried:
 - different browsers
 - different computers
 - clearing my cache
 - resetting password
 - creating a new account

Still cannot log in, so I cannot progress.

**Comment by james-westwood** [comment]
Following a [tutorial](https://medium.com/@CodeYogi/how-to-scrape-websites-behind-a-login-with-python-b8e4efa9f5dd) over at medium. 

@nkshaw23 I will put down some (totally untested) code. I hope this is helpful. Please read the comments.


```python
from bs4 import BeautifulSoup as bs
import requests
from os import path
import re

URL = 'https://data.atoc.org/'
LOGIN_ROUTE = 'user/login?current=node/1'
HEADERS = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)  AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36', 'origin': URL, 'referer': URL + LOGIN_ROUTE}

sesh = requests.session()

csrf_token = sesh.get(URL).cookies['csrftoken'] #This may not be needed!

# probably get the username and password from a txt file that is excluded by .gitignore
login_payload = {
        'login': <yourloginhere>,
        'password': <yourpasswordhere>, 
        'csrfmiddlewaretoken': csrf_token
        }

login_req = sesh.post(URL + LOGIN_ROUTE, headers=HEADERS, data=login_payload)

cookies = login_req.cookies

soup = bs(s.get(URL).text, 'html.parser')

# This should find the first and only zip file on the page
# I think this returns a list, so I am adding [0] to get the string
zip_file = soup.find(re.compile(".*zip"))[0]

# Split it - again this returns a list
zip_name = path.splitext(zip_file)[0]

```

If this works, let's stick it in a function.

**Comment by nkshaw23** [comment]
Running `print(login_req.status_code)` returns 200 which implies I am logged in - but when I go `https://data.atoc.org/data-download` its still saying I need to be logged in.

I am wondering whether we are wasting our time a bit here - the processing of the dataset takes a long time (even with improvements to the method I would imagine it will still take a while). 

Do we want the user to wait through this when they run it? Or do we process ourselves and provide the resulting dataframe as a CSV on sync to be read direct? We could still provide the code if a user wanted to create themselves.

**Comment by jwestw** [comment]
I think we should not expect the user to run this, so it shouldn't be part of the standard pipeline. It's too complicated and computationally heavy and slow.

As I see it the main pipe essentially:
- Buffers highly serviced stops/stations to 500m/1km --> Service area
- Checks if a place of residence is within serviced area
- Counts population within

And pre-processing provides the data the main pipeline needs. 

Pre-processing could be an optional step, run once but not part of the standard pipeline. **It should provide highly serviced stops locations** - which can be **stored as a persistent file and made available**. We might choose to add in other one-off steps to make the pipeline quicker. 

To preempt people who may want to run the pipeline for different levels of service availability, we could create tables for stops serviced at least:
- every hour
- every day
- every 30 mins
- every 15 mins

In the case the user wants to repeat the production of the highly serviced stops dataset, we can leave instructions, including manual steps to create an account with Atoc and download the .cif, .msn other files.

**Comment by nkshaw23** [comment]
@james-westwood  Shall we close this for the timebeing? Opened #307 which looks at saving a copy of the parsed data to be used
