### ISSUE TITLE
Source mid-year population estimates for Scotland

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#322]
After discussions with DSC, they have found mid-year population estimates for Scotland on the [nomis website](https://www.nomisweb.co.uk/default.asp):

![651d2fda-8fee-4169-913b-2a8a86ae65d1](https://user-images.githubusercontent.com/102051068/191526016-04becf22-c76a-43d4-917d-0c2deb36b2cf.jpg)

This ticket requires you to source these estimates using the screenshot above, save them to Sync, and include these in the Scotland script.

**Comment by Antonio-John** [comment]
I think the issue here is we don't have mid year population estimates for Scotland on an output area basis. Therefore, think we are constricted to using 2011 census data.

**Comment by paigeh1** [comment]
@Antonio-John I agree - I think we can close this ticket.
