### ISSUE TITLE
Pre-commit hook for csv files

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#326]
When we run our code, we often ensure that our outputs csv runs, but we do not want this to be added/committed to GitHub.

To resolve this, we could have a pre-commit hook that means we will never commit a csv file to GitHub.

Here are some steps involved:

- [ ] Find pre-commit hook that will do this: @jwestw may be able to help
- [ ] Create pre-commit-config yaml file (info in this [tutorial](https://pre-commit.com/))
- [ ] Put the pre-commit hook code into the yaml file.

**Comment by paigeh1** [comment]
@jwestw Shall I leave this on hold until Tom gets back to us? We will need to make sure we have permission from him to publish his .py file before I can put together the pre-commit yaml file. Also will depend where we want his hook published to e.g. this repo or another one (like you mentioned in our call earlier).

**Comment by jwestw** [comment]
Yes. Let's put this on hold. Shouldn't be long.....
