### ISSUE TITLE
Integrate highly serviced stops into SDG_main

### ISSUE THREAD

**Issue by nkshaw23** [ONSdigital/SDG_11.2.1#330]
We now have two feather files for highly serviced bus and train stops. These need to be integrated into SDG_main. Two main considerations:

- Do we integrate seperately, or merge into one highly serviced stops file (linked to #334 )
- What columns are required from both files

**Comment by james-westwood** [comment]
I think this is taken care of now:

https://github.com/ONSdigital/SDG_11.2.1/blob/d826867e3573fc8b3d944d90e79848dda4cd3ae3/SDG_11.2.1_main.py#L55-L59

@nkshaw23 if you agree we can close this issue.

**Comment by Antonio-John** [comment]
Issue already completed as above screenshot.
