### ISSUE TITLE
Look into PWC in Buffered Stops method

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#347]
We have looked into what is currently happening in the NI data processing to calculate if an OA is served or not. 

- PWC should be a **point** (representing the whole of the OA polygon)
- Stop should be a **polygon**
- Method should be spatial join - probably with the "within" flag

**Comment by jwestw** [comment]
The problem may be at the stage when the geodataframe is created. gpd is not being forced to use the points in the population dataframe and instead it's defaulting to use the OA boundaries.

**Comment by nkshaw23** [comment]
Early investigations show that the PWC dataset `ni_pop_wtd_centr_df` loaded in line 102 is actually a polygon which implies that `pwc_with_pop` is a polygon. This df is used in `only_la_pwc_with_pop` which gets used in the intersection.

Image bewlow shows PWC for E/W/S loaded as points, and PWC for NI loaded as polygons

![image](https://user-images.githubusercontent.com/20166290/204018199-e1425e15-a090-416e-9182-cf92bd195aa2.png)

**Comment by nkshaw23** [comment]
Line 97 in SDG_NI: Replace path to `OA_ni` with path to PWC NI dataset

**Comment by paigeh1** [comment]
I think we can close this now as I have fixed the NI issue with the new dataset @nkshaw23 provided.
