### ISSUE TITLE
Create a tiploc column in the naptan data

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#354]
By extracting [4:] in the Atcocode column, you get the Tiploc code - this applies to "RLY" stoptypes. (May apply to others, to be explored). 

Create the column before any merges occur. 

This might be combined with #353

**Comment by james-westwood** [comment]
To be added to documentation:

> Tiploc means Timing point locations
> TIPLOCs are used by train planners to identify what time trains should arrive at, depart or pass a particular point.  
> They are limited to (up to) seven alpha-characters.
> Tiploc is a unique identifier for train stations (and other points)
> The first 3 digits are the CRS (Computer reservation system) code for the station
