### ISSUE TITLE
Join naptan data on rail data Tiploc code

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#355]
Depends on #354 

Tiploc is a column we have dropped in the rail timetable data, so this needs to be included back in. 

Join on `tiploc` column, as created in #354 

Columns to keep in Naptan in location (easting northing), stop type (for later high/low capactiy) and Atcocode so it can be joined onto bus data.

**Comment by james-westwood** [comment]
created branch: [355-join-naptan-on-tiploc-code](https://github.com/ONSdigital/SDG_11.2.1/tree/355-join-naptan-on-tiploc-code)
