### ISSUE TITLE
FIX: Syntax and data type error

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#367]
1. Numpy is complaing that it doesn't have a data type called np.object
2. I am pretty sure the syntax for line 66 should be `if age_df[col].dtype == ..."` 
3. I think the dtype will simply be `"O"`, as I couldn't track down `np.object` on the [Numpy datatypes page](https://numpy.org/doc/stable/user/basics.types.html). 

This occurs in `data_transform.py`

![image](https://user-images.githubusercontent.com/49570694/211064346-45bb2ede-fc4a-4dca-ba48-375719128955.png)

**Comment by Antonio-John** [comment]
Scotland works :) Need to download some timetable data from sync to test for eng&wal script.

**Comment by Antonio-John** [comment]
This runs for me. Happy to merge this in.
