### ISSUE TITLE
Scotland Output Showing 100% Availability BUG

### ISSUE THREAD

**Issue by Antonio-John** [ONSdigital/SDG_11.2.1#374]
This is is related to #352 looking at Scotland.

Problem
Scotland Showing 100% availability. 

Caused by:
The line ```buffd_la_stops_geo_df = gs.buffer_points(la_stops_geo_df)``` puts 500 metre buffer round all stops to deduce whether people have access to convenient public transport stops.

Within the ```buffer_points``` function a buffer off 500 metre is put round bus stops, 1000 meters round trains. However, the high or low capacity column function which adds a column called ```capacity_type``` if a stop is bus or tram is currently commented out. I think this is awaiting the timetable data to be read in for Scotland have a highly served stops dataframe.

**Comment by Antonio-John** [comment]
The filtered dataframe is read in to Scottish script but for some reason when there is a bus the capacity_type is NaN

**Comment by Antonio-John** [comment]
I suspect the above isn't contributing as works fine in ```main.py``` & the logic in the function is if the capacity type is low then 500metres other 1000metres.

**Comment by Antonio-John** [comment]
This might be an error in all scripts. Here is the stop_geo_df:
![image](https://user-images.githubusercontent.com/74070596/215118406-ea874032-70cd-46d1-bdf0-7b80f85554ad.png)
There are NaN's in capacity type. When there is an NaN as capacity type, the ```buffer_points``` function will give a buffer of a 1000m. (It defaults to 1000m if the capacity type isn't low)

![image](https://user-images.githubusercontent.com/74070596/215118740-c2819b04-6275-4fdb-bdf3-2b4538ddd0b7.png)

Think this is affecting main results unless I am mistaken. Happy to talk through this next week incase I have misunderstood how the stops_geo works.

**Comment by nkshaw23** [comment]
Issue is with line 200 where we intersect the PWC and buffered stops. This intersection captures everything (all 3,170 records) where as in QGIS we can see that it should be 2,877. This is why we are seeing 100% coverage.

![image](https://user-images.githubusercontent.com/20166290/216612607-bca274e8-ea67-4b28-9014-da63cd4dd2f7.png)

**Comment by nkshaw23** [comment]
When trying with `find_points_in_poly` - because `easting` and `northing` are in both datasets, an `easting_left` and `easting_right` etc get created. This causes the function to fail.

![image](https://user-images.githubusercontent.com/20166290/216614129-e8282855-e6e4-4457-afac-f940e0609f33.png)

Assuming we would want methods to match between countries when we merge code, it makes sense to remove `easting` and `northing` from the buffered dataset.

**Comment by nkshaw23** [comment]
For reference, in `main` they only exist in the `la_stops_geo_df` and they dont get carried through. We just keep the geometry of the PWC dataset which contains the points as coordinates. 

I think we should do the same for Scotland.

![image](https://user-images.githubusercontent.com/20166290/216615679-ec502e02-13f2-493f-96f4-5b55fa5487cc.png)

**Comment by nkshaw23** [comment]
Tested for `Fife` and outputs roughly the same between QGIS and script - see #352 for further details. Will make into a MR next week.

**Comment by nkshaw23** [comment]
Code ready but needs some updates from #377 . Might aswell wait until this is merged.
