### ISSUE TITLE
Make a github action to regularly build Mkdocs pages

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#389]
Currently there is an action to deploy the existing pages to gh-pages, but the html pages are not updated if any changes are made in the markdown or rst files.  There should be a gh action to run `sphinx-build -b html docs/source docs/html` and commit/push the changes. 

This was first mentioned in [this issue](https://github.com/ONSdigital/SDG_11.2.1/pull/247) by Nathan.

**Comment by paigeh1** [comment]
We have a github action that are building mkdocs pages
