### ISSUE TITLE
Produce technical documentation using mkdockstrings

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#405]
https://mkdocstrings.github.io/

**Comment by paigeh1** [comment]
What is the purpose of this ticket? I noticed on your recent pull request (PR #410) @jwestw that you have included technical documentation on how to build mkdocs for developers. Is this extra stuff to be added on that we built the docs using mkdocs?

**Comment by jwestw** [comment]
This is duplicated by #397
