### ISSUE TITLE
Create an cloud space for all the data 

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#407]
Probably a Google bucket with read-only access

Deliverables:
- Create a Google bucket
- change the data source to the bucket- mount the bucket as drive
- test that data loads

**Comment by jwestw** [comment]
Look at the code in https://github.com/ONSdigital/research-and-development/blob/develop/src/pipeline.py for inspiration on how to create conditional imports based on a config setting (which indicates choice of environment). In our case we may want to do the same re: imports but the main thing to focus on is the creation of paths (local) vs. signed-urls (cloud). 
Then hopefully most of our existing file read functions will take the signed-url as a "path", just like pandas' dataframe constructor. 

We want to avoid lots of if/else statements throughout the code if possible.

**Comment by jwestw** [comment]
May want to write to bucket which if we do we need to have two things:
- function to write to bucket in the GcpBucket class
- permissions for that service account to write (may already exist)

**Comment by paigeh1** [comment]
Going to download files and host on OneDrive.
