### ISSUE TITLE
Build a function to carry out the method decided on in #392 

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#412]
In #392 a method for calculating the proportion of people at various ages in NI was researched. Whatever came out of the research needs to be implemented in code.

**Comment by paigeh1** [comment]
We have decided that we will use 2011 census estimates in the meantime for mid-year small area population estimates in Northern Ireland. We need to create a function which will take the census 2011 age proportions and apply them to the small area mid-year population estimates.

**Comment by paigeh1** [comment]
Progress so far (so I don't forget!):

- Have created a function that creates the proportions for a given year.
- Have incorporated this age dataframe into the NI pipeline.

Still to do:

- Currently, the pipeline only merges on for 2011 census. I need to think about creating a switch where if ==2011 then we use census but ≠≠ 2011 then we use mid-year estimates. Not sure if that can be done in this ticket!
