### ISSUE TITLE
Write google docs notes into formal documentation

### ISSUE THREAD

**Issue by paigeh1** [ONSdigital/SDG_11.2.1#421]
Link google doc [here](https://docs.google.com/document/d/1mDDPNqYSX2FKbjxsMV6dqNxrN4dLMYxL-dDR9v2TMrM/edit#) and write this work into formal documentation and add into correct place of markdown file.

**Comment by jwestw** [comment]
@paigeh1 I have created a new branch. https://github.com/ONSdigital/SDG_11.2.1/tree/421-google-notes-to-formal

**Comment by paigeh1** [comment]
State caveat of LA boundaries in Scotland #285

**Comment by paigeh1** [comment]
@jwestw need some info on bus portal data (didn't see it in the google docs)

**Comment by paigeh1** [comment]
Completed :

#393 
#297 
#296 
#417 
#323 

as part of this ticket
