### ISSUE TITLE
Split the 2002-2012 pop estimate data into component years

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#439]
The data for the population estimates for 2002 - 2012 comes as one archive from the national archive. The data is in the wrong (long) shape and needs to be both extracted and converted to wide format. The data for each year needs the regions combined, so it represents the whole of the UK and needs to be separated into three datasets based on sex, (m, f and both).

**Comment by paigeh1** [comment]
Complete as of #419
