### ISSUE TITLE
Fix the buffer_points function to accurately calculate 500m radius buffers

### ISSUE THREAD

**Issue by james-westwood** [ONSdigital/SDG_11.2.1#50]
Because CRS is EPSG:27700 and Easting and Northing, a value 500 for the buffer should correspond to 500 metres.

**Comment by jwestw** [comment]
After a conversation with Musa, I finished this on 29th Jan. 

The [code here](https://github.com/ONSdigital/SDG_11.2.1/blob/e390c0cfe9a0c8f2959e2d9937f4b0a9e578abcb/geospatial_mods.py#L45) specifies 500, which is apparently correct. QGis might help to verify this.
