### ISSUE TITLE
Find out how to use the rail timetable data service

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#75]
It might be that the time tables for trains are not available any other way. This could affect many "Stops" in our calculation. http://data.atoc.org/sites/all/themes/atoc/files/RSPS5046.pdf

**Comment by jwestw** [comment]
#256 might be a bit of a duplicate of this

**Comment by nkshaw23** [comment]
Closing as suggested above is duplicated with #256 which has been closed.
