### ISSUE TITLE
create output for qgis and visualise

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#82]
@Musachirikeni I have a few questions about this ticket:
- What is the most universal geo file formats to output to? (e.g. shp, kml or geojson?)
- Are those formats different in size? Which one is most efficient ?
- Would it be helpful to output example maps as jpeg? 
- Should I output a file for the whole country (which would be a lot of data) or a smaller regional one for example?

**Comment by MusaChirikeni** [comment]
Hi James,

The short answer is it depends.

The only real options I would consider for my use are Shapefile and GeoPackage formats.

GeoPackages<https://www.geopackage.org/> (GPKGs) are an open source file format which a easier to handle compared to shapefiles. They are relatively new but gaining popularity quickly.

Shapefiles are an ESRI file format and probably the most used and widely known at the moment. However, one shapefile consists of several files which could make handling a bit awkward.

Documentation<https://geopandas.org/docs/user_guide/io.html> is widely available on working with either file types.
Both are easy to work with in programming or in a GIS software.
At the moment I think its based on personal preference on which one people tend to use more.

I hope this is helpful,

Musa


________________________________
Musa Chirikeni| Geospatial Analyst | Data Architecture
Office for National Statistics | Swyddfa Ystadegau Gwladol
+44 (0)1329 447129 | ***@***.******@***.***> | ***@***.***| @ONSGeography<http://twitter.com/ONSgeography>


From: James Westwood ***@***.***>
Sent: 12 May 2021 11:43
To: ONSdigital/SDG_11.2.1 ***@***.***>
Cc: Chirikeni, Musa ***@***.***>; Mention ***@***.***>
Subject: [ONSdigital/SDG_11.2.1] create output for qgis and visualise (#82)


@MusaChirikeni<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMusaChirikeni&data=04%7C01%7CMusa.Chirikeni%40ons.gov.uk%7C43e50f35798c4f5f679508d91532b507%7C078807bfce824688bce00d811684dc46%7C0%7C0%7C637564129788421903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tLeVWqlNmIO4TqMD6tKv9yqQXTtWOmfQyceHd%2BpuWgM%3D&reserved=0> I have a few questions about this ticket:

  *   What is the most universal geo file formats to output to? (e.g. shp, kml or geojson?)
  *   Would it be helpful to output example maps as jpeg?

-

**Comment by jwestw** [comment]
Done. We have included plots in our writeup
