### ISSUE TITLE
Fix the rounding to zero, in proportion

### ISSUE THREAD

**Issue by jwestw** [ONSdigital/SDG_11.2.1#98]
Either make into float, or change display options or create a new column for proportion.

**Comment by Govej** [comment]
Test

**Comment by jwestw** [comment]
@Govej tagged

**Comment by jwestw** [comment]
@LucyGwilliamAdmin 

This is fixed now. 

Few fixes applied:
- stopped cast the whole table to `int` - I did this to make the "total" and "Served" into ints, which makes sense as they are whole people. However it was forcing the proportions, which were less than 0, to go to 0. 
- cast all the calculated numbers as `str` in the df which is returned by the `served_proportions_disagg` function 
- calculated the percentages rather than the portion (decimal) which served and unserved by public transport. 

Some examples of the output now. 

![image](https://user-images.githubusercontent.com/67740306/118700696-da80f400-b80a-11eb-9818-ef68f996af2e.png)


![image](https://user-images.githubusercontent.com/67740306/118700763-ea98d380-b80a-11eb-9b24-285c2bf21c55.png)


Also fixed:
- Typo in the output table
- Capitalization in the output table

**Comment by jwestw** [comment]
Closed by pull request #108
